/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivitySummary {
  'leaveBalance' : Array<[LeaveType, bigint]>,
  'samplesGiven' : bigint,
  'dailyExpense' : bigint,
  'doctorsVisited' : bigint,
  'chemistOrders' : bigint,
}
export interface Area {
  'id' : AreaId,
  'name' : string,
  'createdBy' : Principal,
  'headquarterId' : bigint,
}
export type AreaId = bigint;
export interface Chemist {
  'id' : ChemistId,
  'contact' : string,
  'name' : string,
  'createdBy' : Principal,
  'address' : string,
  'areaId' : AreaId,
}
export type ChemistId = bigint;
export interface ChemistOrder {
  'status' : OrderStatus,
  'scheme' : string,
  'date' : string,
  'productId' : ProductId,
  'chemistId' : ChemistId,
  'quantity' : bigint,
}
export type DemandOrderStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface DetailingEntry {
  'doctorId' : DoctorId,
  'productIds' : Array<ProductId>,
  'date' : string,
}
export interface Doctor {
  'id' : DoctorId,
  'station' : string,
  'name' : string,
  'createdBy' : Principal,
  'specialization' : string,
  'areaId' : AreaId,
  'qualification' : string,
}
export type DoctorId = bigint;
export interface DoctorInput {
  'station' : string,
  'name' : string,
  'specialization' : string,
  'areaId' : AreaId,
  'qualification' : string,
}
export interface ExpenseEntry {
  'daAmount' : bigint,
  'date' : string,
  'kmTraveled' : bigint,
  'notes' : string,
  'taAmount' : bigint,
}
export interface Headquarter {
  'id' : bigint,
  'name' : string,
  'createdBy' : Principal,
}
export interface LeaveEntry {
  'status' : LeaveStatus,
  'days' : bigint,
  'toDate' : string,
  'fromDate' : string,
  'leaveType' : LeaveType,
  'reason' : string,
}
export type LeaveStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type LeaveType = { 'WithoutPayLeave' : null } |
  { 'CasualLeave' : null } |
  { 'EarnedLeave' : null } |
  { 'SickLeave' : null } |
  { 'PrivilegeLeave' : null };
export interface MRProfile {
  'employeeCode' : string,
  'assignedAreas' : Array<AreaId>,
  'headQuarter' : string,
}
export interface ManagerAreaAssignment { 'areaIds' : Array<AreaId> }
export interface ManagerProfile {
  'managerRole' : ManagerRole,
  'employeeCode' : string,
  'name' : string,
  'headQuarter' : string,
}
export type ManagerRole = { 'ASM' : null } |
  { 'RSM' : null };
export type OrderStatus = { 'pending' : null } |
  { 'fulfilled' : null };
export interface Product {
  'id' : ProductId,
  'code' : string,
  'name' : string,
  'createdBy' : Principal,
}
export type ProductId = bigint;
export interface SampleAllotment {
  'id' : bigint,
  'date' : string,
  'productId' : ProductId,
  'targetPrincipal' : Principal,
  'allocatedBy' : Principal,
  'quantity' : bigint,
}
export interface SampleBalance {
  'balance' : bigint,
  'totalDistributed' : bigint,
  'productId' : ProductId,
  'productName' : string,
  'totalAllotted' : bigint,
}
export interface SampleDemandOrder {
  'id' : bigint,
  'status' : DemandOrderStatus,
  'mrPrincipal' : Principal,
  'date' : string,
  'productId' : ProductId,
  'requestedQty' : bigint,
  'notes' : string,
}
export interface SampleEntry {
  'doctorId' : DoctorId,
  'date' : string,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface UserProfile {
  'employeeCode' : string,
  'name' : string,
  'headQuarter' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArea' : ActorMethod<[string, bigint], AreaId>,
  'addChemist' : ActorMethod<[string, AreaId, string, string], ChemistId>,
  'addChemistOrder' : ActorMethod<
    [ChemistId, string, ProductId, bigint, string],
    undefined
  >,
  'addDoctor' : ActorMethod<[string, string, string, string, AreaId], DoctorId>,
  'addExpense' : ActorMethod<
    [string, bigint, bigint, string, [] | [bigint]],
    undefined
  >,
  'addHeadquarter' : ActorMethod<[string], bigint>,
  'addProduct' : ActorMethod<[string, string], ProductId>,
  'adminAllotSamples' : ActorMethod<
    [Principal, ProductId, bigint, string],
    undefined
  >,
  'adminAssignManagerAreas' : ActorMethod<
    [Principal, Array<AreaId>],
    undefined
  >,
  'adminCreateOrUpdateMRProfile' : ActorMethod<
    [Principal, string, string, Array<AreaId>],
    undefined
  >,
  'adminSaveManagerProfile' : ActorMethod<
    [Principal, string, string, string, ManagerRole],
    undefined
  >,
  'applyLeave' : ActorMethod<
    [LeaveType, string, string, bigint, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddDoctors' : ActorMethod<[Array<DoctorInput>], Array<DoctorId>>,
  'createOrUpdateMRProfile' : ActorMethod<
    [string, string, Array<AreaId>],
    undefined
  >,
  'deleteArea' : ActorMethod<[AreaId], undefined>,
  'deleteDoctor' : ActorMethod<[DoctorId], undefined>,
  'deleteHeadquarter' : ActorMethod<[bigint], undefined>,
  'deleteMRProfile' : ActorMethod<[Principal], undefined>,
  'deleteManagerProfile' : ActorMethod<[Principal], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getActivitySummary' : ActorMethod<[string], ActivitySummary>,
  'getAllAreas' : ActorMethod<[], Array<Area>>,
  'getAllChemists' : ActorMethod<[], Array<Chemist>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllHeadquarters' : ActorMethod<[], Array<Headquarter>>,
  'getAllLeaveApplications' : ActorMethod<
    [],
    Array<[Principal, Array<LeaveEntry>]>
  >,
  'getAllMRProfiles' : ActorMethod<[], Array<[Principal, MRProfile]>>,
  'getAllManagerProfiles' : ActorMethod<[], Array<[Principal, ManagerProfile]>>,
  'getAllPendingUsers' : ActorMethod<[], Array<Principal>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSampleAllotments' : ActorMethod<[], Array<SampleAllotment>>,
  'getAllSampleDemandOrders' : ActorMethod<[], Array<SampleDemandOrder>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChemistOrders' : ActorMethod<[], Array<ChemistOrder>>,
  'getChemistsByArea' : ActorMethod<[AreaId], Array<Chemist>>,
  'getDetailingEntries' : ActorMethod<[], Array<DetailingEntry>>,
  'getDoctorsByArea' : ActorMethod<[AreaId], Array<Doctor>>,
  'getExpenseEntries' : ActorMethod<[], Array<ExpenseEntry>>,
  'getLeaveHistory' : ActorMethod<[], Array<LeaveEntry>>,
  'getMRProfile' : ActorMethod<[], MRProfile>,
  'getManagerAreas' : ActorMethod<[Principal], ManagerAreaAssignment>,
  'getManagerProfile' : ActorMethod<[], [] | [ManagerProfile]>,
  'getMyAllotments' : ActorMethod<[], Array<SampleAllotment>>,
  'getMySampleBalance' : ActorMethod<[], Array<SampleBalance>>,
  'getMySampleDemandOrders' : ActorMethod<[], Array<SampleDemandOrder>>,
  'getSampleEntries' : ActorMethod<[], Array<SampleEntry>>,
  'getTeamDetailingEntries' : ActorMethod<
    [],
    Array<[Principal, Array<DetailingEntry>]>
  >,
  'getTeamExpenseEntries' : ActorMethod<
    [],
    Array<[Principal, Array<ExpenseEntry>]>
  >,
  'getTeamLeaveApplications' : ActorMethod<
    [],
    Array<[Principal, Array<LeaveEntry>]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDetailing' : ActorMethod<[DoctorId, string, Array<ProductId>], undefined>,
  'logSample' : ActorMethod<[DoctorId, string, ProductId, bigint], undefined>,
  'raiseSampleDemandOrder' : ActorMethod<
    [ProductId, bigint, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveManagerProfile' : ActorMethod<
    [string, string, string, ManagerRole],
    undefined
  >,
  'updateArea' : ActorMethod<[AreaId, string, bigint], undefined>,
  'updateDoctor' : ActorMethod<
    [DoctorId, string, string, string, string, AreaId],
    undefined
  >,
  'updateHeadquarter' : ActorMethod<[bigint, string], undefined>,
  'updateLeaveStatus' : ActorMethod<
    [Principal, bigint, LeaveStatus],
    undefined
  >,
  'updateLeaveStatusByManager' : ActorMethod<
    [Principal, bigint, LeaveStatus],
    undefined
  >,
  'updateProduct' : ActorMethod<[ProductId, string, string], undefined>,
  'updateSampleDemandOrderStatus' : ActorMethod<
    [bigint, DemandOrderStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];