/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AreaId = IDL.Nat;
export const ChemistId = IDL.Nat;
export const ProductId = IDL.Nat;
export const DoctorId = IDL.Nat;
export const LeaveType = IDL.Variant({
  'WithoutPayLeave' : IDL.Null,
  'CasualLeave' : IDL.Null,
  'EarnedLeave' : IDL.Null,
  'SickLeave' : IDL.Null,
  'PrivilegeLeave' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivitySummary = IDL.Record({
  'leaveBalance' : IDL.Vec(IDL.Tuple(LeaveType, IDL.Nat)),
  'samplesGiven' : IDL.Nat,
  'dailyExpense' : IDL.Nat,
  'doctorsVisited' : IDL.Nat,
  'chemistOrders' : IDL.Nat,
});
export const Area = IDL.Record({
  'id' : AreaId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
});
export const Chemist = IDL.Record({
  'id' : ChemistId,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'address' : IDL.Text,
  'areaId' : AreaId,
});
export const Doctor = IDL.Record({
  'id' : DoctorId,
  'station' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'specialization' : IDL.Text,
  'areaId' : AreaId,
  'qualification' : IDL.Text,
});
export const LeaveStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const LeaveEntry = IDL.Record({
  'status' : LeaveStatus,
  'days' : IDL.Nat,
  'toDate' : IDL.Text,
  'fromDate' : IDL.Text,
  'leaveType' : LeaveType,
  'reason' : IDL.Text,
});
export const MRProfile = IDL.Record({
  'employeeCode' : IDL.Text,
  'assignedAreas' : IDL.Vec(AreaId),
  'headQuarter' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'employeeCode' : IDL.Text,
  'name' : IDL.Text,
  'headQuarter' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
});
export const ChemistOrder = IDL.Record({
  'status' : OrderStatus,
  'scheme' : IDL.Text,
  'date' : IDL.Text,
  'productId' : ProductId,
  'chemistId' : ChemistId,
  'quantity' : IDL.Nat,
});
export const DetailingEntry = IDL.Record({
  'doctorId' : DoctorId,
  'productIds' : IDL.Vec(ProductId),
  'date' : IDL.Text,
});
export const ExpenseEntry = IDL.Record({
  'daAmount' : IDL.Nat,
  'date' : IDL.Text,
  'kmTraveled' : IDL.Nat,
  'notes' : IDL.Text,
  'taAmount' : IDL.Nat,
});
export const SampleEntry = IDL.Record({
  'doctorId' : DoctorId,
  'date' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArea' : IDL.Func([IDL.Text], [AreaId], []),
  'addChemist' : IDL.Func(
      [IDL.Text, AreaId, IDL.Text, IDL.Text],
      [ChemistId],
      [],
    ),
  'addChemistOrder' : IDL.Func(
      [ChemistId, IDL.Text, ProductId, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addDoctor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, AreaId],
      [DoctorId],
      [],
    ),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'addProduct' : IDL.Func([IDL.Text, IDL.Text], [ProductId], []),
  'applyLeave' : IDL.Func(
      [LeaveType, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateMRProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(AreaId)],
      [],
      [],
    ),
  'getActivitySummary' : IDL.Func([IDL.Text], [ActivitySummary], ['query']),
  'getAllAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
  'getAllChemists' : IDL.Func([], [IDL.Vec(Chemist)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllLeaveApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LeaveEntry)))],
      ['query'],
    ),
  'getAllMRProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, MRProfile))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChemistOrders' : IDL.Func([], [IDL.Vec(ChemistOrder)], ['query']),
  'getChemistsByArea' : IDL.Func([AreaId], [IDL.Vec(Chemist)], ['query']),
  'getDetailingEntries' : IDL.Func([], [IDL.Vec(DetailingEntry)], ['query']),
  'getDoctorsByArea' : IDL.Func([AreaId], [IDL.Vec(Doctor)], ['query']),
  'getExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getLeaveHistory' : IDL.Func([], [IDL.Vec(LeaveEntry)], ['query']),
  'getMRProfile' : IDL.Func([], [MRProfile], ['query']),
  'getSampleEntries' : IDL.Func([], [IDL.Vec(SampleEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDetailing' : IDL.Func([DoctorId, IDL.Text, IDL.Vec(ProductId)], [], []),
  'logSample' : IDL.Func([DoctorId, IDL.Text, ProductId, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLeaveStatus' : IDL.Func([IDL.Principal, IDL.Nat, LeaveStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AreaId = IDL.Nat;
  const ChemistId = IDL.Nat;
  const ProductId = IDL.Nat;
  const DoctorId = IDL.Nat;
  const LeaveType = IDL.Variant({
    'WithoutPayLeave' : IDL.Null,
    'CasualLeave' : IDL.Null,
    'EarnedLeave' : IDL.Null,
    'SickLeave' : IDL.Null,
    'PrivilegeLeave' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivitySummary = IDL.Record({
    'leaveBalance' : IDL.Vec(IDL.Tuple(LeaveType, IDL.Nat)),
    'samplesGiven' : IDL.Nat,
    'dailyExpense' : IDL.Nat,
    'doctorsVisited' : IDL.Nat,
    'chemistOrders' : IDL.Nat,
  });
  const Area = IDL.Record({
    'id' : AreaId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
  });
  const Chemist = IDL.Record({
    'id' : ChemistId,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'address' : IDL.Text,
    'areaId' : AreaId,
  });
  const Doctor = IDL.Record({
    'id' : DoctorId,
    'station' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'specialization' : IDL.Text,
    'areaId' : AreaId,
    'qualification' : IDL.Text,
  });
  const LeaveStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const LeaveEntry = IDL.Record({
    'status' : LeaveStatus,
    'days' : IDL.Nat,
    'toDate' : IDL.Text,
    'fromDate' : IDL.Text,
    'leaveType' : LeaveType,
    'reason' : IDL.Text,
  });
  const MRProfile = IDL.Record({
    'employeeCode' : IDL.Text,
    'assignedAreas' : IDL.Vec(AreaId),
    'headQuarter' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'employeeCode' : IDL.Text,
    'name' : IDL.Text,
    'headQuarter' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
  });
  const ChemistOrder = IDL.Record({
    'status' : OrderStatus,
    'scheme' : IDL.Text,
    'date' : IDL.Text,
    'productId' : ProductId,
    'chemistId' : ChemistId,
    'quantity' : IDL.Nat,
  });
  const DetailingEntry = IDL.Record({
    'doctorId' : DoctorId,
    'productIds' : IDL.Vec(ProductId),
    'date' : IDL.Text,
  });
  const ExpenseEntry = IDL.Record({
    'daAmount' : IDL.Nat,
    'date' : IDL.Text,
    'kmTraveled' : IDL.Nat,
    'notes' : IDL.Text,
    'taAmount' : IDL.Nat,
  });
  const SampleEntry = IDL.Record({
    'doctorId' : DoctorId,
    'date' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArea' : IDL.Func([IDL.Text], [AreaId], []),
    'addChemist' : IDL.Func(
        [IDL.Text, AreaId, IDL.Text, IDL.Text],
        [ChemistId],
        [],
      ),
    'addChemistOrder' : IDL.Func(
        [ChemistId, IDL.Text, ProductId, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, AreaId],
        [DoctorId],
        [],
      ),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'addProduct' : IDL.Func([IDL.Text, IDL.Text], [ProductId], []),
    'applyLeave' : IDL.Func(
        [LeaveType, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateMRProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(AreaId)],
        [],
        [],
      ),
    'getActivitySummary' : IDL.Func([IDL.Text], [ActivitySummary], ['query']),
    'getAllAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
    'getAllChemists' : IDL.Func([], [IDL.Vec(Chemist)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllLeaveApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LeaveEntry)))],
        ['query'],
      ),
    'getAllMRProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, MRProfile))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChemistOrders' : IDL.Func([], [IDL.Vec(ChemistOrder)], ['query']),
    'getChemistsByArea' : IDL.Func([AreaId], [IDL.Vec(Chemist)], ['query']),
    'getDetailingEntries' : IDL.Func([], [IDL.Vec(DetailingEntry)], ['query']),
    'getDoctorsByArea' : IDL.Func([AreaId], [IDL.Vec(Doctor)], ['query']),
    'getExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getLeaveHistory' : IDL.Func([], [IDL.Vec(LeaveEntry)], ['query']),
    'getMRProfile' : IDL.Func([], [MRProfile], ['query']),
    'getSampleEntries' : IDL.Func([], [IDL.Vec(SampleEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDetailing' : IDL.Func([DoctorId, IDL.Text, IDL.Vec(ProductId)], [], []),
    'logSample' : IDL.Func([DoctorId, IDL.Text, ProductId, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLeaveStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, LeaveStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };