/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivitySummary {
  'leaveBalance' : Array<[LeaveType, bigint]>,
  'samplesGiven' : bigint,
  'dailyExpense' : bigint,
  'doctorsVisited' : bigint,
  'chemistOrders' : bigint,
}
export interface Area {
  'id' : AreaId,
  'name' : string,
  'createdBy' : Principal,
  'headquarterId' : bigint,
}
export type AreaId = bigint;
export interface CRMDemand {
  'id' : CRMDemandId,
  'status' : CRMDemandStatus,
  'doctorId' : DoctorId,
  'date' : string,
  'notes' : string,
  'raisedBy' : Principal,
  'doctorName' : string,
  'amount' : bigint,
  'raiserName' : string,
  'adminRemarks' : string,
}
export type CRMDemandId = bigint;
export type CRMDemandStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Chemist {
  'id' : ChemistId,
  'contact' : string,
  'name' : string,
  'createdBy' : Principal,
  'address' : string,
  'areaId' : AreaId,
}
export type ChemistId = bigint;
export interface ChemistOrder {
  'status' : OrderStatus,
  'scheme' : string,
  'date' : string,
  'productId' : ProductId,
  'chemistId' : ChemistId,
  'quantity' : bigint,
}
export type DemandOrderStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface DetailingEntry {
  'doctorId' : DoctorId,
  'productIds' : Array<ProductId>,
  'date' : string,
}
export interface Doctor {
  'id' : DoctorId,
  'station' : string,
  'name' : string,
  'mobileNumber' : [] | [string],
  'dob' : [] | [string],
  'createdBy' : Principal,
  'specialization' : string,
  'areaId' : AreaId,
  'qualification' : string,
}
export type DoctorId = bigint;
export interface DoctorInput {
  'station' : string,
  'name' : string,
  'mobileNumber' : [] | [string],
  'dob' : [] | [string],
  'specialization' : string,
  'areaId' : AreaId,
  'qualification' : string,
}
export interface ExpenseEntry {
  'latitude' : [] | [number],
  'daType' : string,
  'daAmount' : bigint,
  'date' : string,
  'kmTraveled' : bigint,
  'longitude' : [] | [number],
  'notes' : string,
  'workingArea' : string,
  'taAmount' : bigint,
}
export interface GPSTrace {
  'latitude' : number,
  'createdBy' : Principal,
  'longitude' : number,
  'timestamp' : bigint,
  'accuracy' : number,
}
export interface GiftArticle {
  'id' : GiftArticleId,
  'name' : string,
  'description' : string,
}
export type GiftArticleId = bigint;
export interface GiftDemandOrder {
  'id' : GiftDemandOrderId,
  'status' : GiftDemandOrderStatus,
  'mrPrincipal' : Principal,
  'date' : string,
  'giftArticleName' : string,
  'notes' : string,
  'giftArticleId' : GiftArticleId,
  'quantity' : bigint,
  'adminRemarks' : string,
}
export type GiftDemandOrderId = bigint;
export type GiftDemandOrderStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface GiftDistribution {
  'id' : GiftDistributionId,
  'doctorId' : DoctorId,
  'date' : string,
  'distributedBy' : Principal,
  'giftArticleName' : string,
  'giftArticleId' : GiftArticleId,
  'quantity' : bigint,
  'doctorName' : string,
}
export type GiftDistributionId = bigint;
export interface Headquarter {
  'id' : bigint,
  'name' : string,
  'createdBy' : Principal,
}
export interface LeaveEntry {
  'status' : LeaveStatus,
  'days' : bigint,
  'toDate' : string,
  'fromDate' : string,
  'leaveType' : LeaveType,
  'reason' : string,
}
export type LeaveStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type LeaveType = { 'WithoutPayLeave' : null } |
  { 'CasualLeave' : null } |
  { 'EarnedLeave' : null } |
  { 'SickLeave' : null } |
  { 'PrivilegeLeave' : null };
export interface LocationData {
  'latitude' : number,
  'userName' : string,
  'userRole' : string,
  'longitude' : number,
  'timestamp' : bigint,
  'accuracy' : number,
}
export interface MRProfile {
  'employeeCode' : string,
  'assignedAreas' : Array<AreaId>,
  'headQuarter' : string,
}
export interface ManagerAreaAssignment { 'areaIds' : Array<AreaId> }
export interface ManagerProfile {
  'managerRole' : ManagerRole,
  'employeeCode' : string,
  'name' : string,
  'headQuarter' : string,
}
export type ManagerRole = { 'ASM' : null } |
  { 'RSM' : null };
export type OrderStatus = { 'pending' : null } |
  { 'fulfilled' : null };
export interface Product {
  'id' : ProductId,
  'code' : string,
  'name' : string,
  'createdBy' : Principal,
}
export type ProductId = bigint;
export interface SampleAllotment {
  'id' : bigint,
  'date' : string,
  'productId' : ProductId,
  'targetPrincipal' : Principal,
  'allocatedBy' : Principal,
  'quantity' : bigint,
}
export interface SampleBalance {
  'balance' : bigint,
  'totalDistributed' : bigint,
  'productId' : ProductId,
  'productName' : string,
  'totalAllotted' : bigint,
}
export interface SampleDemandOrder {
  'id' : bigint,
  'status' : DemandOrderStatus,
  'mrPrincipal' : Principal,
  'date' : string,
  'productId' : ProductId,
  'requestedQty' : bigint,
  'notes' : string,
}
export interface SampleEntry {
  'doctorId' : DoctorId,
  'date' : string,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface TADASettingsV3 {
  'mrTaPerKm' : bigint,
  'mrDaHQ' : bigint,
  'rsmDaHQ' : bigint,
  'rsmDaOutStation' : bigint,
  'rsmTaPerKm' : bigint,
  'asmDaOutStation' : bigint,
  'asmDaHQ' : bigint,
  'asmTaPerKm' : bigint,
  'mrDaExStation' : bigint,
  'rsmDaExStation' : bigint,
  'asmDaExStation' : bigint,
  'mrDaOutStation' : bigint,
}
export interface UserProfile {
  'employeeCode' : string,
  'name' : string,
  'headQuarter' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkingPlan {
  'id' : WorkingPlanId,
  'content' : string,
  'date' : string,
  'createdAt' : bigint,
  'workingMode' : string,
  'workingWith' : [] | [string],
  'stationType' : string,
  'principalId' : Principal,
}
export type WorkingPlanId = bigint;

export type AnnouncementCategory = { 'LatestProduct' : null } | { 'UpcomingProduct' : null } | { 'LatestScheme' : null } | { 'NewGiftArticle' : null };
export type AnnouncementId = bigint;
export interface AdminAnnouncement {
  'id' : AnnouncementId,
  'title' : string,
  'body' : string,
  'category' : AnnouncementCategory,
  'createdAt' : bigint,
  'isActive' : boolean,
  'createdBy' : Principal,
  'imageUrl' : [] | [string],
}
export type HolidayId = bigint;
export interface Holiday {
  'id' : HolidayId,
  'name' : string,
  'date' : string,
  'description' : string,
  'createdBy' : Principal,
}
export interface WorkingPlanInput {
  'content' : string,
  'date' : string,
  'workingMode' : string,
  'workingWith' : [] | [string],
  'stationType' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArea' : ActorMethod<[string, bigint], AreaId>,
  'addChemist' : ActorMethod<[string, AreaId, string, string], ChemistId>,
  'addChemistOrder' : ActorMethod<
    [ChemistId, string, ProductId, bigint, string],
    undefined
  >,
  'addDoctor' : ActorMethod<[string, string, string, string, AreaId, [] | [string], [] | [string]], DoctorId>,
  'addExpenseWithGeoTag' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      [] | [bigint],
      string,
      string,
      [] | [number],
      [] | [number],
    ],
    undefined
  >,
  'addGPSTrace' : ActorMethod<[number, number, number], undefined>,
  'addGiftArticle' : ActorMethod<[string, string], GiftArticleId>,
  'addHeadquarter' : ActorMethod<[string], bigint>,
  'addProduct' : ActorMethod<[string, string], ProductId>,
  'addWorkingPlan' : ActorMethod<[WorkingPlanInput], WorkingPlanId>,
  'adminAllotSamples' : ActorMethod<
    [Principal, ProductId, bigint, string],
    undefined
  >,
  'adminAssignManagerAreas' : ActorMethod<
    [Principal, Array<AreaId>],
    undefined
  >,
  'adminCreateOrUpdateMRProfile' : ActorMethod<
    [Principal, string, string, Array<AreaId>],
    undefined
  >,
  'adminGetAllWorkingPlans' : ActorMethod<[], Array<WorkingPlan>>,
  'adminGetTADASettings' : ActorMethod<[], TADASettingsV3>,
  'adminResetAllReportData' : ActorMethod<[], undefined>,
  'adminSaveManagerProfile' : ActorMethod<
    [Principal, string, string, string, ManagerRole],
    undefined
  >,
  'adminSetTADASettings' : ActorMethod<[TADASettingsV3], undefined>,
  'applyLeave' : ActorMethod<
    [LeaveType, string, string, bigint, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddDoctors' : ActorMethod<[Array<DoctorInput>], Array<DoctorId>>,
  'createOrUpdateMRProfile' : ActorMethod<
    [string, string, Array<AreaId>],
    undefined
  >,
  'deleteArea' : ActorMethod<[AreaId], undefined>,
  'deleteDoctor' : ActorMethod<[DoctorId], undefined>,
  'deleteGiftArticle' : ActorMethod<[GiftArticleId], undefined>,
  'deleteHeadquarter' : ActorMethod<[bigint], undefined>,
  'deleteMRProfile' : ActorMethod<[Principal], undefined>,
  'deleteManagerProfile' : ActorMethod<[Principal], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteWorkingPlan' : ActorMethod<[WorkingPlanId], undefined>,
  'emergencyRestoreAdmin' : ActorMethod<[], undefined>,
  'getActiveUserLocations' : ActorMethod<[], Array<[Principal, LocationData]>>,
  'getActivitySummary' : ActorMethod<[string], ActivitySummary>,
  'getAllAreas' : ActorMethod<[], Array<Area>>,
  'getAllCRMDemands' : ActorMethod<[], Array<CRMDemand>>,
  'getAllChemists' : ActorMethod<[], Array<Chemist>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllGiftArticles' : ActorMethod<[], Array<GiftArticle>>,
  'getAllGiftDemandOrders' : ActorMethod<[], Array<GiftDemandOrder>>,
  'getAllGiftDistributions' : ActorMethod<[], Array<GiftDistribution>>,
  'getAllHeadquarters' : ActorMethod<[], Array<Headquarter>>,
  'getAllLeaveApplications' : ActorMethod<
    [],
    Array<[Principal, Array<LeaveEntry>]>
  >,
  'getAllMRProfiles' : ActorMethod<[], Array<[Principal, MRProfile]>>,
  'getAllManagerProfiles' : ActorMethod<[], Array<[Principal, ManagerProfile]>>,
  'getAllPendingUsers' : ActorMethod<[], Array<Principal>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSampleAllotments' : ActorMethod<[], Array<SampleAllotment>>,
  'getAllSampleDemandOrders' : ActorMethod<[], Array<SampleDemandOrder>>,
  'getAllUserLatestLocations' : ActorMethod<
    [],
    Array<[Principal, LocationData]>
  >,
  'getAllUserLatestLocationsByRole' : ActorMethod<
    [],
    Array<[Principal, LocationData]>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerRoleInfo' : ActorMethod<
    [],
    { 'managerRole' : [] | [string], 'baseRole' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChemistOrders' : ActorMethod<[], Array<ChemistOrder>>,
  'getChemistsByArea' : ActorMethod<[AreaId], Array<Chemist>>,
  'getDetailingEntries' : ActorMethod<[], Array<DetailingEntry>>,
  'getDoctorsByArea' : ActorMethod<[AreaId], Array<Doctor>>,
  'getExpenseEntries' : ActorMethod<[], Array<ExpenseEntry>>,
  'getGPSTraces' : ActorMethod<[Principal], Array<GPSTrace>>,
  'getLatestLocation' : ActorMethod<[Principal], [] | [LocationData]>,
  'getLeaveHistory' : ActorMethod<[], Array<LeaveEntry>>,
  'getMRProfile' : ActorMethod<[], MRProfile>,
  'getManagerAreas' : ActorMethod<[Principal], ManagerAreaAssignment>,
  'getManagerProfile' : ActorMethod<[], [] | [ManagerProfile]>,
  'getMyAllotments' : ActorMethod<[], Array<SampleAllotment>>,
  'getMyCRMDemands' : ActorMethod<[], Array<CRMDemand>>,
  'getMyGiftDemandOrders' : ActorMethod<[], Array<GiftDemandOrder>>,
  'getMyGiftDistributions' : ActorMethod<[], Array<GiftDistribution>>,
  'getMySampleBalance' : ActorMethod<[], Array<SampleBalance>>,
  'getMySampleDemandOrders' : ActorMethod<[], Array<SampleDemandOrder>>,
  'getMyWorkingPlans' : ActorMethod<[], Array<WorkingPlan>>,
  'getSampleEntries' : ActorMethod<[], Array<SampleEntry>>,
  'getTeamDetailingEntries' : ActorMethod<
    [],
    Array<[Principal, Array<DetailingEntry>]>
  >,
  'getTeamExpenseEntries' : ActorMethod<
    [],
    Array<[Principal, Array<ExpenseEntry>]>
  >,
  'getTeamLeaveApplications' : ActorMethod<
    [],
    Array<[Principal, Array<LeaveEntry>]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTraceBetweenTimes' : ActorMethod<
    [Principal, bigint, bigint],
    Array<GPSTrace>
  >,
  'isAdminInitialized' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDetailing' : ActorMethod<[DoctorId, string, Array<ProductId>], undefined>,
  'logGiftDistribution' : ActorMethod<
    [DoctorId, string, GiftArticleId, string, bigint, string],
    undefined
  >,
  'logSample' : ActorMethod<[DoctorId, string, ProductId, bigint], undefined>,
  'raiseCRMDemand' : ActorMethod<
    [DoctorId, string, bigint, string, string, string],
    undefined
  >,
  'raiseGiftDemandOrder' : ActorMethod<
    [GiftArticleId, string, bigint, string, string],
    undefined
  >,
  'raiseSampleDemandOrder' : ActorMethod<
    [ProductId, bigint, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveManagerProfile' : ActorMethod<
    [string, string, string, ManagerRole],
    undefined
  >,
  'updateArea' : ActorMethod<[AreaId, string, bigint], undefined>,
  'updateCRMDemandStatus' : ActorMethod<
    [CRMDemandId, CRMDemandStatus, string],
    undefined
  >,
  'updateDoctor' : ActorMethod<
    [DoctorId, string, string, string, string, AreaId, [] | [string], [] | [string]],
    undefined
  >,
  'updateGiftArticle' : ActorMethod<[GiftArticleId, string, string], undefined>,
  'updateGiftDemandOrderStatus' : ActorMethod<
    [GiftDemandOrderId, GiftDemandOrderStatus, string],
    undefined
  >,
  'updateHeadquarter' : ActorMethod<[bigint, string], undefined>,
  'updateLatestLocation' : ActorMethod<[LocationData], undefined>,
  'updateLeaveStatus' : ActorMethod<
    [Principal, bigint, LeaveStatus],
    undefined
  >,
  'updateLeaveStatusByManager' : ActorMethod<
    [Principal, bigint, LeaveStatus],
    undefined
  >,
  'updateProduct' : ActorMethod<[ProductId, string, string], undefined>,
  'adminAddHoliday' : ActorMethod<[string, string, string], HolidayId>,
  'adminUpdateHoliday' : ActorMethod<[HolidayId, string, string, string], undefined>,
  'adminDeleteHoliday' : ActorMethod<[HolidayId], undefined>,
  'getAllHolidays' : ActorMethod<[], Array<Holiday>>,
  'adminAddAnnouncement' : ActorMethod<[string, string, AnnouncementCategory, [] | [string]], AnnouncementId>,
  'adminUpdateAnnouncement' : ActorMethod<[AnnouncementId, string, string, AnnouncementCategory, boolean, [] | [string]], boolean>,
  'adminDeleteAnnouncement' : ActorMethod<[AnnouncementId], boolean>,
  'getActiveAnnouncements' : ActorMethod<[], Array<AdminAnnouncement>>,
  'getAllAnnouncements' : ActorMethod<[], Array<AdminAnnouncement>>,
  'recordUserAnnouncementView' : ActorMethod<[string], undefined>,
  'hasUserSeenAnnouncementsToday' : ActorMethod<[string], boolean>,

  'updateSampleDemandOrderStatus' : ActorMethod<
    [bigint, DemandOrderStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];