/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AreaId = IDL.Nat;
export const ChemistId = IDL.Nat;
export const ProductId = IDL.Nat;
export const DoctorId = IDL.Nat;
export const GiftArticleId = IDL.Nat;
export const ManagerRole = IDL.Variant({ 'ASM' : IDL.Null, 'RSM' : IDL.Null });
export const LeaveType = IDL.Variant({
  'WithoutPayLeave' : IDL.Null,
  'CasualLeave' : IDL.Null,
  'EarnedLeave' : IDL.Null,
  'SickLeave' : IDL.Null,
  'PrivilegeLeave' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DoctorInput = IDL.Record({
  'station' : IDL.Text,
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'areaId' : AreaId,
  'qualification' : IDL.Text,
});
export const ActivitySummary = IDL.Record({
  'leaveBalance' : IDL.Vec(IDL.Tuple(LeaveType, IDL.Nat)),
  'samplesGiven' : IDL.Nat,
  'dailyExpense' : IDL.Nat,
  'doctorsVisited' : IDL.Nat,
  'chemistOrders' : IDL.Nat,
});
export const Area = IDL.Record({
  'id' : AreaId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'headquarterId' : IDL.Nat,
});
export const CRMDemandId = IDL.Nat;
export const CRMDemandStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CRMDemand = IDL.Record({
  'id' : CRMDemandId,
  'status' : CRMDemandStatus,
  'doctorId' : DoctorId,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'raisedBy' : IDL.Principal,
  'doctorName' : IDL.Text,
  'amount' : IDL.Nat,
  'raiserName' : IDL.Text,
  'adminRemarks' : IDL.Text,
});
export const Chemist = IDL.Record({
  'id' : ChemistId,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'address' : IDL.Text,
  'areaId' : AreaId,
});
export const Doctor = IDL.Record({
  'id' : DoctorId,
  'station' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'specialization' : IDL.Text,
  'areaId' : AreaId,
  'qualification' : IDL.Text,
});
export const GiftArticle = IDL.Record({
  'id' : GiftArticleId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const GiftDemandOrderId = IDL.Nat;
export const GiftDemandOrderStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const GiftDemandOrder = IDL.Record({
  'id' : GiftDemandOrderId,
  'status' : GiftDemandOrderStatus,
  'mrPrincipal' : IDL.Principal,
  'date' : IDL.Text,
  'giftArticleName' : IDL.Text,
  'notes' : IDL.Text,
  'giftArticleId' : GiftArticleId,
  'quantity' : IDL.Nat,
  'adminRemarks' : IDL.Text,
});
export const GiftDistributionId = IDL.Nat;
export const GiftDistribution = IDL.Record({
  'id' : GiftDistributionId,
  'doctorId' : DoctorId,
  'date' : IDL.Text,
  'distributedBy' : IDL.Principal,
  'giftArticleName' : IDL.Text,
  'giftArticleId' : GiftArticleId,
  'quantity' : IDL.Nat,
  'doctorName' : IDL.Text,
});
export const Headquarter = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
});
export const LeaveStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const LeaveEntry = IDL.Record({
  'status' : LeaveStatus,
  'days' : IDL.Nat,
  'toDate' : IDL.Text,
  'fromDate' : IDL.Text,
  'leaveType' : LeaveType,
  'reason' : IDL.Text,
});
export const MRProfile = IDL.Record({
  'employeeCode' : IDL.Text,
  'assignedAreas' : IDL.Vec(AreaId),
  'headQuarter' : IDL.Text,
});
export const ManagerProfile = IDL.Record({
  'managerRole' : ManagerRole,
  'employeeCode' : IDL.Text,
  'name' : IDL.Text,
  'headQuarter' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
});
export const SampleAllotment = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'productId' : ProductId,
  'targetPrincipal' : IDL.Principal,
  'allocatedBy' : IDL.Principal,
  'quantity' : IDL.Nat,
});
export const DemandOrderStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const SampleDemandOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : DemandOrderStatus,
  'mrPrincipal' : IDL.Principal,
  'date' : IDL.Text,
  'productId' : ProductId,
  'requestedQty' : IDL.Nat,
  'notes' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'employeeCode' : IDL.Text,
  'name' : IDL.Text,
  'headQuarter' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
});
export const ChemistOrder = IDL.Record({
  'status' : OrderStatus,
  'scheme' : IDL.Text,
  'date' : IDL.Text,
  'productId' : ProductId,
  'chemistId' : ChemistId,
  'quantity' : IDL.Nat,
});
export const DetailingEntry = IDL.Record({
  'doctorId' : DoctorId,
  'productIds' : IDL.Vec(ProductId),
  'date' : IDL.Text,
});
export const ExpenseEntry = IDL.Record({
  'daAmount' : IDL.Nat,
  'date' : IDL.Text,
  'kmTraveled' : IDL.Nat,
  'notes' : IDL.Text,
  'taAmount' : IDL.Nat,
});
export const ManagerAreaAssignment = IDL.Record({
  'areaIds' : IDL.Vec(AreaId),
});
export const SampleBalance = IDL.Record({
  'balance' : IDL.Nat,
  'totalDistributed' : IDL.Nat,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'totalAllotted' : IDL.Nat,
});
export const SampleEntry = IDL.Record({
  'doctorId' : DoctorId,
  'date' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArea' : IDL.Func([IDL.Text, IDL.Nat], [AreaId], []),
  'addChemist' : IDL.Func(
      [IDL.Text, AreaId, IDL.Text, IDL.Text],
      [ChemistId],
      [],
    ),
  'addChemistOrder' : IDL.Func(
      [ChemistId, IDL.Text, ProductId, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addDoctor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, AreaId],
      [DoctorId],
      [],
    ),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'addGiftArticle' : IDL.Func([IDL.Text, IDL.Text], [GiftArticleId], []),
  'addHeadquarter' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addProduct' : IDL.Func([IDL.Text, IDL.Text], [ProductId], []),
  'adminAllotSamples' : IDL.Func(
      [IDL.Principal, ProductId, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'adminAssignManagerAreas' : IDL.Func(
      [IDL.Principal, IDL.Vec(AreaId)],
      [],
      [],
    ),
  'adminCreateOrUpdateMRProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Vec(AreaId)],
      [],
      [],
    ),
  'adminSaveManagerProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, ManagerRole],
      [],
      [],
    ),
  'emergencyRestoreAdmin' : IDL.Func([], [], []),
  'applyLeave' : IDL.Func(
      [LeaveType, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAddDoctors' : IDL.Func([IDL.Vec(DoctorInput)], [IDL.Vec(DoctorId)], []),
  'createOrUpdateMRProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(AreaId)],
      [],
      [],
    ),
  'deleteArea' : IDL.Func([AreaId], [], []),
  'deleteDoctor' : IDL.Func([DoctorId], [], []),
  'deleteGiftArticle' : IDL.Func([GiftArticleId], [], []),
  'deleteHeadquarter' : IDL.Func([IDL.Nat], [], []),
  'deleteMRProfile' : IDL.Func([IDL.Principal], [], []),
  'deleteManagerProfile' : IDL.Func([IDL.Principal], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getActivitySummary' : IDL.Func([IDL.Text], [ActivitySummary], ['query']),
  'getAllAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
  'getAllCRMDemands' : IDL.Func([], [IDL.Vec(CRMDemand)], ['query']),
  'getAllChemists' : IDL.Func([], [IDL.Vec(Chemist)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllGiftArticles' : IDL.Func([], [IDL.Vec(GiftArticle)], ['query']),
  'getAllGiftDemandOrders' : IDL.Func(
      [],
      [IDL.Vec(GiftDemandOrder)],
      ['query'],
    ),
  'getAllGiftDistributions' : IDL.Func(
      [],
      [IDL.Vec(GiftDistribution)],
      ['query'],
    ),
  'getAllHeadquarters' : IDL.Func([], [IDL.Vec(Headquarter)], ['query']),
  'getAllLeaveApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LeaveEntry)))],
      ['query'],
    ),
  'getAllMRProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, MRProfile))],
      ['query'],
    ),
  'getAllManagerProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ManagerProfile))],
      ['query'],
    ),
  'getAllPendingUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSampleAllotments' : IDL.Func(
      [],
      [IDL.Vec(SampleAllotment)],
      ['query'],
    ),
  'getAllSampleDemandOrders' : IDL.Func(
      [],
      [IDL.Vec(SampleDemandOrder)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChemistOrders' : IDL.Func([], [IDL.Vec(ChemistOrder)], ['query']),
  'getChemistsByArea' : IDL.Func([AreaId], [IDL.Vec(Chemist)], ['query']),
  'getDetailingEntries' : IDL.Func([], [IDL.Vec(DetailingEntry)], ['query']),
  'getDoctorsByArea' : IDL.Func([AreaId], [IDL.Vec(Doctor)], ['query']),
  'getExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getLeaveHistory' : IDL.Func([], [IDL.Vec(LeaveEntry)], ['query']),
  'getMRProfile' : IDL.Func([], [MRProfile], ['query']),
  'getManagerAreas' : IDL.Func(
      [IDL.Principal],
      [ManagerAreaAssignment],
      ['query'],
    ),
  'getManagerProfile' : IDL.Func([], [IDL.Opt(ManagerProfile)], ['query']),
  'getMyAllotments' : IDL.Func([], [IDL.Vec(SampleAllotment)], ['query']),
  'getMyCRMDemands' : IDL.Func([], [IDL.Vec(CRMDemand)], ['query']),
  'getMyGiftDemandOrders' : IDL.Func([], [IDL.Vec(GiftDemandOrder)], ['query']),
  'getMyGiftDistributions' : IDL.Func(
      [],
      [IDL.Vec(GiftDistribution)],
      ['query'],
    ),
  'getMySampleBalance' : IDL.Func([], [IDL.Vec(SampleBalance)], ['query']),
  'getMySampleDemandOrders' : IDL.Func(
      [],
      [IDL.Vec(SampleDemandOrder)],
      ['query'],
    ),
  'getSampleEntries' : IDL.Func([], [IDL.Vec(SampleEntry)], ['query']),
  'getTeamDetailingEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(DetailingEntry)))],
      ['query'],
    ),
  'getTeamExpenseEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ExpenseEntry)))],
      ['query'],
    ),
  'getTeamLeaveApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LeaveEntry)))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDetailing' : IDL.Func([DoctorId, IDL.Text, IDL.Vec(ProductId)], [], []),
  'logGiftDistribution' : IDL.Func(
      [DoctorId, IDL.Text, GiftArticleId, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'logSample' : IDL.Func([DoctorId, IDL.Text, ProductId, IDL.Nat], [], []),
  'raiseCRMDemand' : IDL.Func(
      [DoctorId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'raiseGiftDemandOrder' : IDL.Func(
      [GiftArticleId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'raiseSampleDemandOrder' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveManagerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ManagerRole],
      [],
      [],
    ),
  'updateArea' : IDL.Func([AreaId, IDL.Text, IDL.Nat], [], []),
  'updateCRMDemandStatus' : IDL.Func(
      [CRMDemandId, CRMDemandStatus, IDL.Text],
      [],
      [],
    ),
  'updateDoctor' : IDL.Func(
      [DoctorId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AreaId],
      [],
      [],
    ),
  'updateGiftArticle' : IDL.Func([GiftArticleId, IDL.Text, IDL.Text], [], []),
  'updateGiftDemandOrderStatus' : IDL.Func(
      [GiftDemandOrderId, GiftDemandOrderStatus, IDL.Text],
      [],
      [],
    ),
  'updateHeadquarter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateLeaveStatus' : IDL.Func([IDL.Principal, IDL.Nat, LeaveStatus], [], []),
  'updateLeaveStatusByManager' : IDL.Func(
      [IDL.Principal, IDL.Nat, LeaveStatus],
      [],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, IDL.Text, IDL.Text], [], []),
  'updateSampleDemandOrderStatus' : IDL.Func(
      [IDL.Nat, DemandOrderStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AreaId = IDL.Nat;
  const ChemistId = IDL.Nat;
  const ProductId = IDL.Nat;
  const DoctorId = IDL.Nat;
  const GiftArticleId = IDL.Nat;
  const ManagerRole = IDL.Variant({ 'ASM' : IDL.Null, 'RSM' : IDL.Null });
  const LeaveType = IDL.Variant({
    'WithoutPayLeave' : IDL.Null,
    'CasualLeave' : IDL.Null,
    'EarnedLeave' : IDL.Null,
    'SickLeave' : IDL.Null,
    'PrivilegeLeave' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DoctorInput = IDL.Record({
    'station' : IDL.Text,
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'areaId' : AreaId,
    'qualification' : IDL.Text,
  });
  const ActivitySummary = IDL.Record({
    'leaveBalance' : IDL.Vec(IDL.Tuple(LeaveType, IDL.Nat)),
    'samplesGiven' : IDL.Nat,
    'dailyExpense' : IDL.Nat,
    'doctorsVisited' : IDL.Nat,
    'chemistOrders' : IDL.Nat,
  });
  const Area = IDL.Record({
    'id' : AreaId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'headquarterId' : IDL.Nat,
  });
  const CRMDemandId = IDL.Nat;
  const CRMDemandStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CRMDemand = IDL.Record({
    'id' : CRMDemandId,
    'status' : CRMDemandStatus,
    'doctorId' : DoctorId,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'raisedBy' : IDL.Principal,
    'doctorName' : IDL.Text,
    'amount' : IDL.Nat,
    'raiserName' : IDL.Text,
    'adminRemarks' : IDL.Text,
  });
  const Chemist = IDL.Record({
    'id' : ChemistId,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'address' : IDL.Text,
    'areaId' : AreaId,
  });
  const Doctor = IDL.Record({
    'id' : DoctorId,
    'station' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'specialization' : IDL.Text,
    'areaId' : AreaId,
    'qualification' : IDL.Text,
  });
  const GiftArticle = IDL.Record({
    'id' : GiftArticleId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const GiftDemandOrderId = IDL.Nat;
  const GiftDemandOrderStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const GiftDemandOrder = IDL.Record({
    'id' : GiftDemandOrderId,
    'status' : GiftDemandOrderStatus,
    'mrPrincipal' : IDL.Principal,
    'date' : IDL.Text,
    'giftArticleName' : IDL.Text,
    'notes' : IDL.Text,
    'giftArticleId' : GiftArticleId,
    'quantity' : IDL.Nat,
    'adminRemarks' : IDL.Text,
  });
  const GiftDistributionId = IDL.Nat;
  const GiftDistribution = IDL.Record({
    'id' : GiftDistributionId,
    'doctorId' : DoctorId,
    'date' : IDL.Text,
    'distributedBy' : IDL.Principal,
    'giftArticleName' : IDL.Text,
    'giftArticleId' : GiftArticleId,
    'quantity' : IDL.Nat,
    'doctorName' : IDL.Text,
  });
  const Headquarter = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
  });
  const LeaveStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const LeaveEntry = IDL.Record({
    'status' : LeaveStatus,
    'days' : IDL.Nat,
    'toDate' : IDL.Text,
    'fromDate' : IDL.Text,
    'leaveType' : LeaveType,
    'reason' : IDL.Text,
  });
  const MRProfile = IDL.Record({
    'employeeCode' : IDL.Text,
    'assignedAreas' : IDL.Vec(AreaId),
    'headQuarter' : IDL.Text,
  });
  const ManagerProfile = IDL.Record({
    'managerRole' : ManagerRole,
    'employeeCode' : IDL.Text,
    'name' : IDL.Text,
    'headQuarter' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
  });
  const SampleAllotment = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'productId' : ProductId,
    'targetPrincipal' : IDL.Principal,
    'allocatedBy' : IDL.Principal,
    'quantity' : IDL.Nat,
  });
  const DemandOrderStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const SampleDemandOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : DemandOrderStatus,
    'mrPrincipal' : IDL.Principal,
    'date' : IDL.Text,
    'productId' : ProductId,
    'requestedQty' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'employeeCode' : IDL.Text,
    'name' : IDL.Text,
    'headQuarter' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
  });
  const ChemistOrder = IDL.Record({
    'status' : OrderStatus,
    'scheme' : IDL.Text,
    'date' : IDL.Text,
    'productId' : ProductId,
    'chemistId' : ChemistId,
    'quantity' : IDL.Nat,
  });
  const DetailingEntry = IDL.Record({
    'doctorId' : DoctorId,
    'productIds' : IDL.Vec(ProductId),
    'date' : IDL.Text,
  });
  const ExpenseEntry = IDL.Record({
    'daAmount' : IDL.Nat,
    'date' : IDL.Text,
    'kmTraveled' : IDL.Nat,
    'notes' : IDL.Text,
    'taAmount' : IDL.Nat,
  });
  const ManagerAreaAssignment = IDL.Record({ 'areaIds' : IDL.Vec(AreaId) });
  const SampleBalance = IDL.Record({
    'balance' : IDL.Nat,
    'totalDistributed' : IDL.Nat,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'totalAllotted' : IDL.Nat,
  });
  const SampleEntry = IDL.Record({
    'doctorId' : DoctorId,
    'date' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArea' : IDL.Func([IDL.Text, IDL.Nat], [AreaId], []),
    'addChemist' : IDL.Func(
        [IDL.Text, AreaId, IDL.Text, IDL.Text],
        [ChemistId],
        [],
      ),
    'addChemistOrder' : IDL.Func(
        [ChemistId, IDL.Text, ProductId, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, AreaId],
        [DoctorId],
        [],
      ),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'addGiftArticle' : IDL.Func([IDL.Text, IDL.Text], [GiftArticleId], []),
    'addHeadquarter' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addProduct' : IDL.Func([IDL.Text, IDL.Text], [ProductId], []),
    'adminAllotSamples' : IDL.Func(
        [IDL.Principal, ProductId, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'adminAssignManagerAreas' : IDL.Func(
        [IDL.Principal, IDL.Vec(AreaId)],
        [],
        [],
      ),
    'adminCreateOrUpdateMRProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Vec(AreaId)],
        [],
        [],
      ),
    'adminSaveManagerProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, ManagerRole],
        [],
        [],
      ),
    'emergencyRestoreAdmin' : IDL.Func([], [], []),
  'applyLeave' : IDL.Func(
        [LeaveType, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAddDoctors' : IDL.Func(
        [IDL.Vec(DoctorInput)],
        [IDL.Vec(DoctorId)],
        [],
      ),
    'createOrUpdateMRProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(AreaId)],
        [],
        [],
      ),
    'deleteArea' : IDL.Func([AreaId], [], []),
    'deleteDoctor' : IDL.Func([DoctorId], [], []),
    'deleteGiftArticle' : IDL.Func([GiftArticleId], [], []),
    'deleteHeadquarter' : IDL.Func([IDL.Nat], [], []),
    'deleteMRProfile' : IDL.Func([IDL.Principal], [], []),
    'deleteManagerProfile' : IDL.Func([IDL.Principal], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getActivitySummary' : IDL.Func([IDL.Text], [ActivitySummary], ['query']),
    'getAllAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
    'getAllCRMDemands' : IDL.Func([], [IDL.Vec(CRMDemand)], ['query']),
    'getAllChemists' : IDL.Func([], [IDL.Vec(Chemist)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllGiftArticles' : IDL.Func([], [IDL.Vec(GiftArticle)], ['query']),
    'getAllGiftDemandOrders' : IDL.Func(
        [],
        [IDL.Vec(GiftDemandOrder)],
        ['query'],
      ),
    'getAllGiftDistributions' : IDL.Func(
        [],
        [IDL.Vec(GiftDistribution)],
        ['query'],
      ),
    'getAllHeadquarters' : IDL.Func([], [IDL.Vec(Headquarter)], ['query']),
    'getAllLeaveApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LeaveEntry)))],
        ['query'],
      ),
    'getAllMRProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, MRProfile))],
        ['query'],
      ),
    'getAllManagerProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ManagerProfile))],
        ['query'],
      ),
    'getAllPendingUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSampleAllotments' : IDL.Func(
        [],
        [IDL.Vec(SampleAllotment)],
        ['query'],
      ),
    'getAllSampleDemandOrders' : IDL.Func(
        [],
        [IDL.Vec(SampleDemandOrder)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChemistOrders' : IDL.Func([], [IDL.Vec(ChemistOrder)], ['query']),
    'getChemistsByArea' : IDL.Func([AreaId], [IDL.Vec(Chemist)], ['query']),
    'getDetailingEntries' : IDL.Func([], [IDL.Vec(DetailingEntry)], ['query']),
    'getDoctorsByArea' : IDL.Func([AreaId], [IDL.Vec(Doctor)], ['query']),
    'getExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getLeaveHistory' : IDL.Func([], [IDL.Vec(LeaveEntry)], ['query']),
    'getMRProfile' : IDL.Func([], [MRProfile], ['query']),
    'getManagerAreas' : IDL.Func(
        [IDL.Principal],
        [ManagerAreaAssignment],
        ['query'],
      ),
    'getManagerProfile' : IDL.Func([], [IDL.Opt(ManagerProfile)], ['query']),
    'getMyAllotments' : IDL.Func([], [IDL.Vec(SampleAllotment)], ['query']),
    'getMyCRMDemands' : IDL.Func([], [IDL.Vec(CRMDemand)], ['query']),
    'getMyGiftDemandOrders' : IDL.Func(
        [],
        [IDL.Vec(GiftDemandOrder)],
        ['query'],
      ),
    'getMyGiftDistributions' : IDL.Func(
        [],
        [IDL.Vec(GiftDistribution)],
        ['query'],
      ),
    'getMySampleBalance' : IDL.Func([], [IDL.Vec(SampleBalance)], ['query']),
    'getMySampleDemandOrders' : IDL.Func(
        [],
        [IDL.Vec(SampleDemandOrder)],
        ['query'],
      ),
    'getSampleEntries' : IDL.Func([], [IDL.Vec(SampleEntry)], ['query']),
    'getTeamDetailingEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(DetailingEntry)))],
        ['query'],
      ),
    'getTeamExpenseEntries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ExpenseEntry)))],
        ['query'],
      ),
    'getTeamLeaveApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(LeaveEntry)))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDetailing' : IDL.Func([DoctorId, IDL.Text, IDL.Vec(ProductId)], [], []),
    'logGiftDistribution' : IDL.Func(
        [DoctorId, IDL.Text, GiftArticleId, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'logSample' : IDL.Func([DoctorId, IDL.Text, ProductId, IDL.Nat], [], []),
    'raiseCRMDemand' : IDL.Func(
        [DoctorId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'raiseGiftDemandOrder' : IDL.Func(
        [GiftArticleId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'raiseSampleDemandOrder' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveManagerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ManagerRole],
        [],
        [],
      ),
    'updateArea' : IDL.Func([AreaId, IDL.Text, IDL.Nat], [], []),
    'updateCRMDemandStatus' : IDL.Func(
        [CRMDemandId, CRMDemandStatus, IDL.Text],
        [],
        [],
      ),
    'updateDoctor' : IDL.Func(
        [DoctorId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AreaId],
        [],
        [],
      ),
    'updateGiftArticle' : IDL.Func([GiftArticleId, IDL.Text, IDL.Text], [], []),
    'updateGiftDemandOrderStatus' : IDL.Func(
        [GiftDemandOrderId, GiftDemandOrderStatus, IDL.Text],
        [],
        [],
      ),
    'updateHeadquarter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateLeaveStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, LeaveStatus],
        [],
        [],
      ),
    'updateLeaveStatusByManager' : IDL.Func(
        [IDL.Principal, IDL.Nat, LeaveStatus],
        [],
        [],
      ),
    'updateProduct' : IDL.Func([ProductId, IDL.Text, IDL.Text], [], []),
    'updateSampleDemandOrderStatus' : IDL.Func(
        [IDL.Nat, DemandOrderStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };