/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ManagerProfile {
    managerRole: ManagerRole;
    employeeCode: string;
    name: string;
    headQuarter: string;
}
export interface MRProfile {
    employeeCode: string;
    assignedAreas: Array<AreaId>;
    headQuarter: string;
}
export interface DoctorInput {
    station: string;
    name: string;
    specialization: string;
    areaId: AreaId;
    qualification: string;
}
export interface SampleDemandOrder {
    id: bigint;
    status: DemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    productId: ProductId;
    requestedQty: bigint;
    notes: string;
}
export interface Doctor {
    id: DoctorId;
    station: string;
    name: string;
    createdBy: Principal;
    specialization: string;
    areaId: AreaId;
    qualification: string;
}
export interface ExpenseEntry {
    daAmount: bigint;
    date: string;
    kmTraveled: bigint;
    notes: string;
    taAmount: bigint;
}
export interface Chemist {
    id: ChemistId;
    contact: string;
    name: string;
    createdBy: Principal;
    address: string;
    areaId: AreaId;
}
export interface SampleBalance {
    balance: bigint;
    totalDistributed: bigint;
    productId: ProductId;
    productName: string;
    totalAllotted: bigint;
}
export interface SampleEntry {
    doctorId: DoctorId;
    date: string;
    productId: ProductId;
    quantity: bigint;
}
export type DoctorId = bigint;
export interface DetailingEntry {
    doctorId: DoctorId;
    productIds: Array<ProductId>;
    date: string;
}
export type ChemistId = bigint;
export interface Headquarter {
    id: bigint;
    name: string;
    createdBy: Principal;
}
export interface LeaveEntry {
    status: LeaveStatus;
    days: bigint;
    toDate: string;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
}
export interface ChemistOrder {
    status: OrderStatus;
    scheme: string;
    date: string;
    productId: ProductId;
    chemistId: ChemistId;
    quantity: bigint;
}
export interface ActivitySummary {
    leaveBalance: Array<[LeaveType, bigint]>;
    samplesGiven: bigint;
    dailyExpense: bigint;
    doctorsVisited: bigint;
    chemistOrders: bigint;
}
export interface Area {
    id: AreaId;
    name: string;
    createdBy: Principal;
    headquarterId: bigint;
}
export type AreaId = bigint;
export type ProductId = bigint;
export interface SampleAllotment {
    id: bigint;
    date: string;
    productId: ProductId;
    targetPrincipal: Principal;
    allocatedBy: Principal;
    quantity: bigint;
}
export interface UserProfile {
    employeeCode: string;
    name: string;
    headQuarter: string;
}
export interface Product {
    id: ProductId;
    code: string;
    name: string;
    createdBy: Principal;
}
export enum LeaveStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum LeaveType {
    WithoutPayLeave = "WithoutPayLeave",
    CasualLeave = "CasualLeave",
    EarnedLeave = "EarnedLeave",
    SickLeave = "SickLeave",
    PrivilegeLeave = "PrivilegeLeave"
}
export enum ManagerRole {
    ASM = "ASM",
    RSM = "RSM"
}
export enum OrderStatus {
    pending = "pending",
    fulfilled = "fulfilled"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addArea(name: string, headquarterId: bigint): Promise<AreaId>;
    addChemist(name: string, areaId: AreaId, address: string, contact: string): Promise<ChemistId>;
    addChemistOrder(chemistId: ChemistId, date: string, productId: ProductId, quantity: bigint, scheme: string): Promise<void>;
    addDoctor(name: string, qualification: string, station: string, specialization: string, areaId: AreaId): Promise<DoctorId>;
    addExpense(date: string, kmTraveled: bigint, daAmount: bigint, notes: string, taAmountOpt: bigint | null): Promise<void>;
    addHeadquarter(name: string): Promise<bigint>;
    addProduct(name: string, code: string): Promise<ProductId>;
    adminAllotSamples(target: Principal, productId: ProductId, quantity: bigint, date: string): Promise<void>;
    adminCreateOrUpdateMRProfile(mrPrincipal: Principal, employeeCode: string, headQuarter: string, assignedAreas: Array<AreaId>): Promise<void>;
    adminSaveManagerProfile(target: Principal, name: string, employeeCode: string, headQuarter: string, managerRole: ManagerRole): Promise<void>;
    applyLeave(leaveType: LeaveType, fromDate: string, toDate: string, days: bigint, reason: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkAddDoctors(doctorsInput: Array<DoctorInput>): Promise<Array<DoctorId>>;
    createOrUpdateMRProfile(employeeCode: string, headQuarter: string, assignedAreas: Array<AreaId>): Promise<void>;
    deleteDoctor(id: DoctorId): Promise<void>;
    deleteHeadquarter(id: bigint): Promise<void>;
    deleteMRProfile(mrPrincipal: Principal): Promise<void>;
    deleteManagerProfile(target: Principal): Promise<void>;
    deleteProduct(id: ProductId): Promise<void>;
    getActivitySummary(date: string): Promise<ActivitySummary>;
    getAllAreas(): Promise<Array<Area>>;
    getAllChemists(): Promise<Array<Chemist>>;
    getAllDoctors(): Promise<Array<Doctor>>;
    getAllHeadquarters(): Promise<Array<Headquarter>>;
    getAllLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>>;
    getAllMRProfiles(): Promise<Array<[Principal, MRProfile]>>;
    getAllManagerProfiles(): Promise<Array<[Principal, ManagerProfile]>>;
    getAllPendingUsers(): Promise<Array<Principal>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllSampleAllotments(): Promise<Array<SampleAllotment>>;
    getAllSampleDemandOrders(): Promise<Array<SampleDemandOrder>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChemistOrders(): Promise<Array<ChemistOrder>>;
    getChemistsByArea(areaId: AreaId): Promise<Array<Chemist>>;
    getDetailingEntries(): Promise<Array<DetailingEntry>>;
    getDoctorsByArea(areaId: AreaId): Promise<Array<Doctor>>;
    getExpenseEntries(): Promise<Array<ExpenseEntry>>;
    getLeaveHistory(): Promise<Array<LeaveEntry>>;
    getMRProfile(): Promise<MRProfile>;
    getManagerProfile(): Promise<ManagerProfile | null>;
    getMyAllotments(): Promise<Array<SampleAllotment>>;
    getMySampleBalance(): Promise<Array<SampleBalance>>;
    getMySampleDemandOrders(): Promise<Array<SampleDemandOrder>>;
    getSampleEntries(): Promise<Array<SampleEntry>>;
    getTeamDetailingEntries(): Promise<Array<[Principal, Array<DetailingEntry>]>>;
    getTeamExpenseEntries(): Promise<Array<[Principal, Array<ExpenseEntry>]>>;
    getTeamLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logDetailing(doctorId: DoctorId, date: string, productIds: Array<ProductId>): Promise<void>;
    logSample(doctorId: DoctorId, date: string, productId: ProductId, quantity: bigint): Promise<void>;
    raiseSampleDemandOrder(productId: ProductId, requestedQty: bigint, date: string, notes: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveManagerProfile(name: string, employeeCode: string, headQuarter: string, managerRole: ManagerRole): Promise<void>;
    updateDoctor(id: DoctorId, name: string, qualification: string, station: string, specialization: string, areaId: AreaId): Promise<void>;
    updateHeadquarter(id: bigint, name: string): Promise<void>;
    updateLeaveStatus(mrPrincipal: Principal, leaveIndex: bigint, newStatus: LeaveStatus): Promise<void>;
    updateLeaveStatusByManager(mrPrincipal: Principal, leaveIndex: bigint, newStatus: LeaveStatus): Promise<void>;
    updateProduct(id: ProductId, name: string, code: string): Promise<void>;
    updateSampleDemandOrderStatus(orderId: bigint, newStatus: DemandOrderStatus): Promise<void>;
}
import type { ActivitySummary as _ActivitySummary, ChemistId as _ChemistId, ChemistOrder as _ChemistOrder, DemandOrderStatus as _DemandOrderStatus, LeaveEntry as _LeaveEntry, LeaveStatus as _LeaveStatus, LeaveType as _LeaveType, ManagerProfile as _ManagerProfile, ManagerRole as _ManagerRole, OrderStatus as _OrderStatus, ProductId as _ProductId, SampleDemandOrder as _SampleDemandOrder, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addArea(arg0: string, arg1: bigint): Promise<AreaId> {
        if (this.processError) {
            try {
                const result = await this.actor.addArea(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArea(arg0, arg1);
            return result;
        }
    }
    async addChemist(arg0: string, arg1: AreaId, arg2: string, arg3: string): Promise<ChemistId> {
        if (this.processError) {
            try {
                const result = await this.actor.addChemist(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChemist(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addChemistOrder(arg0: ChemistId, arg1: string, arg2: ProductId, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChemistOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChemistOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addDoctor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: AreaId): Promise<DoctorId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addExpense(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addHeadquarter(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeadquarter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeadquarter(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1);
            return result;
        }
    }
    async adminAllotSamples(arg0: Principal, arg1: ProductId, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAllotSamples(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAllotSamples(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminCreateOrUpdateMRProfile(arg0: Principal, arg1: string, arg2: string, arg3: Array<AreaId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateOrUpdateMRProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateOrUpdateMRProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminSaveManagerProfile(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: ManagerRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSaveManagerProfile(arg0, arg1, arg2, arg3, to_candid_ManagerRole_n2(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSaveManagerProfile(arg0, arg1, arg2, arg3, to_candid_ManagerRole_n2(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async applyLeave(arg0: LeaveType, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyLeave(to_candid_LeaveType_n4(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyLeave(to_candid_LeaveType_n4(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAddDoctors(arg0: Array<DoctorInput>): Promise<Array<DoctorId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddDoctors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddDoctors(arg0);
            return result;
        }
    }
    async createOrUpdateMRProfile(arg0: string, arg1: string, arg2: Array<AreaId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateMRProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateMRProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteDoctor(arg0: DoctorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteHeadquarter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHeadquarter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHeadquarter(arg0);
            return result;
        }
    }
    async deleteMRProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMRProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMRProfile(arg0);
            return result;
        }
    }
    async deleteManagerProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManagerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManagerProfile(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getActivitySummary(arg0: string): Promise<ActivitySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitySummary(arg0);
                return from_candid_ActivitySummary_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitySummary(arg0);
            return from_candid_ActivitySummary_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAreas(): Promise<Array<Area>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAreas();
            return result;
        }
    }
    async getAllChemists(): Promise<Array<Chemist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChemists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChemists();
            return result;
        }
    }
    async getAllDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return result;
        }
    }
    async getAllHeadquarters(): Promise<Array<Headquarter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHeadquarters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHeadquarters();
            return result;
        }
    }
    async getAllLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaveApplications();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaveApplications();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMRProfiles(): Promise<Array<[Principal, MRProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMRProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMRProfiles();
            return result;
        }
    }
    async getAllManagerProfiles(): Promise<Array<[Principal, ManagerProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllManagerProfiles();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllManagerProfiles();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingUsers();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllSampleAllotments(): Promise<Array<SampleAllotment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSampleAllotments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSampleAllotments();
            return result;
        }
    }
    async getAllSampleDemandOrders(): Promise<Array<SampleDemandOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSampleDemandOrders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSampleDemandOrders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChemistOrders(): Promise<Array<ChemistOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChemistOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChemistOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChemistsByArea(arg0: AreaId): Promise<Array<Chemist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChemistsByArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChemistsByArea(arg0);
            return result;
        }
    }
    async getDetailingEntries(): Promise<Array<DetailingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetailingEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetailingEntries();
            return result;
        }
    }
    async getDoctorsByArea(arg0: AreaId): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorsByArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorsByArea(arg0);
            return result;
        }
    }
    async getExpenseEntries(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseEntries();
            return result;
        }
    }
    async getLeaveHistory(): Promise<Array<LeaveEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveHistory();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveHistory();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMRProfile(): Promise<MRProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMRProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMRProfile();
            return result;
        }
    }
    async getManagerProfile(): Promise<ManagerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagerProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagerProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAllotments(): Promise<Array<SampleAllotment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAllotments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAllotments();
            return result;
        }
    }
    async getMySampleBalance(): Promise<Array<SampleBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySampleBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySampleBalance();
            return result;
        }
    }
    async getMySampleDemandOrders(): Promise<Array<SampleDemandOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySampleDemandOrders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySampleDemandOrders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSampleEntries(): Promise<Array<SampleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleEntries();
            return result;
        }
    }
    async getTeamDetailingEntries(): Promise<Array<[Principal, Array<DetailingEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamDetailingEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamDetailingEntries();
            return result;
        }
    }
    async getTeamExpenseEntries(): Promise<Array<[Principal, Array<ExpenseEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamExpenseEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamExpenseEntries();
            return result;
        }
    }
    async getTeamLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamLeaveApplications();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamLeaveApplications();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logDetailing(arg0: DoctorId, arg1: string, arg2: Array<ProductId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDetailing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDetailing(arg0, arg1, arg2);
            return result;
        }
    }
    async logSample(arg0: DoctorId, arg1: string, arg2: ProductId, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSample(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSample(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async raiseSampleDemandOrder(arg0: ProductId, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.raiseSampleDemandOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.raiseSampleDemandOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveManagerProfile(arg0: string, arg1: string, arg2: string, arg3: ManagerRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveManagerProfile(arg0, arg1, arg2, to_candid_ManagerRole_n2(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveManagerProfile(arg0, arg1, arg2, to_candid_ManagerRole_n2(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateDoctor(arg0: DoctorId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: AreaId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateHeadquarter(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeadquarter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeadquarter(arg0, arg1);
            return result;
        }
    }
    async updateLeaveStatus(arg0: Principal, arg1: bigint, arg2: LeaveStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveStatus(arg0, arg1, to_candid_LeaveStatus_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveStatus(arg0, arg1, to_candid_LeaveStatus_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateLeaveStatusByManager(arg0: Principal, arg1: bigint, arg2: LeaveStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveStatusByManager(arg0, arg1, to_candid_LeaveStatus_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveStatusByManager(arg0, arg1, to_candid_LeaveStatus_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSampleDemandOrderStatus(arg0: bigint, arg1: DemandOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleDemandOrderStatus(arg0, to_candid_DemandOrderStatus_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleDemandOrderStatus(arg0, to_candid_DemandOrderStatus_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivitySummary_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivitySummary): ActivitySummary {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ChemistOrder_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChemistOrder): ChemistOrder {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DemandOrderStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DemandOrderStatus): DemandOrderStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveEntry): LeaveEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveType): LeaveType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerProfile): ManagerProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerRole): ManagerRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SampleDemandOrder_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleDemandOrder): SampleDemandOrder {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ManagerProfile]): ManagerProfile | null {
    return value.length === 0 ? null : from_candid_ManagerProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeaveStatus;
    days: bigint;
    toDate: string;
    fromDate: string;
    leaveType: _LeaveType;
    reason: string;
}): {
    status: LeaveStatus;
    days: bigint;
    toDate: string;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
} {
    return {
        status: from_candid_LeaveStatus_n19(_uploadFile, _downloadFile, value.status),
        days: value.days,
        toDate: value.toDate,
        fromDate: value.fromDate,
        leaveType: from_candid_LeaveType_n12(_uploadFile, _downloadFile, value.leaveType),
        reason: value.reason
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    managerRole: _ManagerRole;
    employeeCode: string;
    name: string;
    headQuarter: string;
}): {
    managerRole: ManagerRole;
    employeeCode: string;
    name: string;
    headQuarter: string;
} {
    return {
        managerRole: from_candid_ManagerRole_n25(_uploadFile, _downloadFile, value.managerRole),
        employeeCode: value.employeeCode,
        name: value.name,
        headQuarter: value.headQuarter
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    productId: _ProductId;
    requestedQty: bigint;
    notes: string;
}): {
    id: bigint;
    status: DemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    productId: ProductId;
    requestedQty: bigint;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_DemandOrderStatus_n30(_uploadFile, _downloadFile, value.status),
        mrPrincipal: value.mrPrincipal,
        date: value.date,
        productId: value.productId,
        requestedQty: value.requestedQty,
        notes: value.notes
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    scheme: string;
    date: string;
    productId: _ProductId;
    chemistId: _ChemistId;
    quantity: bigint;
}): {
    status: OrderStatus;
    scheme: string;
    date: string;
    productId: ProductId;
    chemistId: ChemistId;
    quantity: bigint;
} {
    return {
        status: from_candid_OrderStatus_n37(_uploadFile, _downloadFile, value.status),
        scheme: value.scheme,
        date: value.date,
        productId: value.productId,
        chemistId: value.chemistId,
        quantity: value.quantity
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leaveBalance: Array<[_LeaveType, bigint]>;
    samplesGiven: bigint;
    dailyExpense: bigint;
    doctorsVisited: bigint;
    chemistOrders: bigint;
}): {
    leaveBalance: Array<[LeaveType, bigint]>;
    samplesGiven: bigint;
    dailyExpense: bigint;
    doctorsVisited: bigint;
    chemistOrders: bigint;
} {
    return {
        leaveBalance: from_candid_vec_n10(_uploadFile, _downloadFile, value.leaveBalance),
        samplesGiven: value.samplesGiven,
        dailyExpense: value.dailyExpense,
        doctorsVisited: value.doctorsVisited,
        chemistOrders: value.chemistOrders
    };
}
function from_candid_tuple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_LeaveType, bigint]): [LeaveType, bigint] {
    return [
        from_candid_LeaveType_n12(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_LeaveEntry>]): [Principal, Array<LeaveEntry>] {
    return [
        value[0],
        from_candid_vec_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _ManagerProfile]): [Principal, ManagerProfile] {
    return [
        value[0],
        from_candid_ManagerProfile_n23(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    WithoutPayLeave: null;
} | {
    CasualLeave: null;
} | {
    EarnedLeave: null;
} | {
    SickLeave: null;
} | {
    PrivilegeLeave: null;
}): LeaveType {
    return "WithoutPayLeave" in value ? LeaveType.WithoutPayLeave : "CasualLeave" in value ? LeaveType.CasualLeave : "EarnedLeave" in value ? LeaveType.EarnedLeave : "SickLeave" in value ? LeaveType.SickLeave : "PrivilegeLeave" in value ? LeaveType.PrivilegeLeave : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): LeaveStatus {
    return "Approved" in value ? LeaveStatus.Approved : "Rejected" in value ? LeaveStatus.Rejected : "Pending" in value ? LeaveStatus.Pending : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ASM: null;
} | {
    RSM: null;
}): ManagerRole {
    return "ASM" in value ? ManagerRole.ASM : "RSM" in value ? ManagerRole.RSM : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    fulfilled: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "fulfilled" in value ? OrderStatus.fulfilled : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_LeaveType, bigint]>): Array<[LeaveType, bigint]> {
    return value.map((x)=>from_candid_tuple_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_LeaveEntry>]>): Array<[Principal, Array<LeaveEntry>]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveEntry>): Array<LeaveEntry> {
    return value.map((x)=>from_candid_LeaveEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _ManagerProfile]>): Array<[Principal, ManagerProfile]> {
    return value.map((x)=>from_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SampleDemandOrder>): Array<SampleDemandOrder> {
    return value.map((x)=>from_candid_SampleDemandOrder_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChemistOrder>): Array<ChemistOrder> {
    return value.map((x)=>from_candid_ChemistOrder_n35(_uploadFile, _downloadFile, x));
}
function to_candid_DemandOrderStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DemandOrderStatus): _DemandOrderStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): _LeaveType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ManagerRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerRole): _ManagerRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerRole): {
    ASM: null;
} | {
    RSM: null;
} {
    return value == ManagerRole.ASM ? {
        ASM: null
    } : value == ManagerRole.RSM ? {
        RSM: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == LeaveStatus.Approved ? {
        Approved: null
    } : value == LeaveStatus.Rejected ? {
        Rejected: null
    } : value == LeaveStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): {
    WithoutPayLeave: null;
} | {
    CasualLeave: null;
} | {
    EarnedLeave: null;
} | {
    SickLeave: null;
} | {
    PrivilegeLeave: null;
} {
    return value == LeaveType.WithoutPayLeave ? {
        WithoutPayLeave: null
    } : value == LeaveType.CasualLeave ? {
        CasualLeave: null
    } : value == LeaveType.EarnedLeave ? {
        EarnedLeave: null
    } : value == LeaveType.SickLeave ? {
        SickLeave: null
    } : value == LeaveType.PrivilegeLeave ? {
        PrivilegeLeave: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
