/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ManagerProfile {
    managerRole: ManagerRole;
    employeeCode: string;
    name: string;
    headQuarter: string;
}
export interface MRProfile {
    employeeCode: string;
    assignedAreas: Array<AreaId>;
    headQuarter: string;
}
export interface GiftDistribution {
    id: GiftDistributionId;
    doctorId: DoctorId;
    date: string;
    distributedBy: Principal;
    giftArticleName: string;
    giftArticleId: GiftArticleId;
    quantity: bigint;
    doctorName: string;
}
export interface CRMDemand {
    id: CRMDemandId;
    status: CRMDemandStatus;
    doctorId: DoctorId;
    date: string;
    notes: string;
    raisedBy: Principal;
    doctorName: string;
    amount: bigint;
    raiserName: string;
    adminRemarks: string;
}
export interface DoctorInput {
    station: string;
    name: string;
    mobileNumber?: string;
    dob?: [] | [string];
    specialization: string;
    areaId: AreaId;
    qualification: string;
}
export interface WorkingPlan {
    id: WorkingPlanId;
    content: string;
    date: string;
    createdAt: bigint;
    workingMode: string;
    workingWith?: string;
    stationType: string;
    principalId: Principal;
}
export interface GPSTrace {
    latitude: number;
    createdBy: Principal;
    longitude: number;
    timestamp: bigint;
    accuracy: number;
}
export interface WorkingPlanInput {
    content: string;
    date: string;
    workingMode: string;
    workingWith?: string;
    stationType: string;
}
export interface SampleDemandOrder {
    id: bigint;
    status: DemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    productId: ProductId;
    requestedQty: bigint;
    notes: string;
}
export type CRMDemandId = bigint;
export interface ManagerAreaAssignment {
    areaIds: Array<AreaId>;
}
export interface Doctor {
    id: DoctorId;
    station: string;
    name: string;
    mobileNumber?: string;
    dob?: [] | [string];
    createdBy: Principal;
    specialization: string;
    areaId: AreaId;
    qualification: string;
}
export interface GiftDemandOrder {
    id: GiftDemandOrderId;
    status: GiftDemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    giftArticleName: string;
    notes: string;
    giftArticleId: GiftArticleId;
    quantity: bigint;
    adminRemarks: string;
}
export interface ExpenseEntry {
    latitude?: number;
    daType: string;
    daAmount: bigint;
    date: string;
    kmTraveled: bigint;
    longitude?: number;
    notes: string;
    workingArea: string;
    taAmount: bigint;
}
export interface SampleBalance {
    balance: bigint;
    totalDistributed: bigint;
    productId: ProductId;
    productName: string;
    totalAllotted: bigint;
}
export interface Chemist {
    id: ChemistId;
    contact: string;
    name: string;
    createdBy: Principal;
    address: string;
    areaId: AreaId;
}
export type GiftArticleId = bigint;
export type WorkingPlanId = bigint;
export interface SampleEntry {
    doctorId: DoctorId;
    date: string;
    productId: ProductId;
    quantity: bigint;
}
export type GiftDemandOrderId = bigint;
export type DoctorId = bigint;
export interface DetailingEntry {
    doctorId: DoctorId;
    productIds: Array<ProductId>;
    date: string;
}
export type ChemistId = bigint;
export interface GiftArticle {
    id: GiftArticleId;
    name: string;
    description: string;
}
export interface LocationData {
    latitude: number;
    userName: string;
    userRole: string;
    longitude: number;
    timestamp: bigint;
    accuracy: number;
}
export interface Headquarter {
    id: bigint;
    name: string;
    createdBy: Principal;
}
export interface LeaveEntry {
    status: LeaveStatus;
    days: bigint;
    toDate: string;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
}
export interface ChemistOrder {
    status: OrderStatus;
    scheme: string;
    date: string;
    productId: ProductId;
    chemistId: ChemistId;
    quantity: bigint;
}
export interface ActivitySummary {
    leaveBalance: Array<[LeaveType, bigint]>;
    samplesGiven: bigint;
    dailyExpense: bigint;
    doctorsVisited: bigint;
    chemistOrders: bigint;
}
export interface TADASettingsV3 {
    mrTaPerKm: bigint;
    mrDaHQ: bigint;
    rsmDaHQ: bigint;
    rsmDaOutStation: bigint;
    rsmTaPerKm: bigint;
    asmDaOutStation: bigint;
    asmDaHQ: bigint;
    asmTaPerKm: bigint;
    mrDaExStation: bigint;
    rsmDaExStation: bigint;
    asmDaExStation: bigint;
    mrDaOutStation: bigint;
}
export interface Area {
    id: AreaId;
    name: string;
    createdBy: Principal;
    headquarterId: bigint;
}
export type AreaId = bigint;
export type ProductId = bigint;
export type GiftDistributionId = bigint;
export interface SampleAllotment {
    id: bigint;
    date: string;
    productId: ProductId;
    targetPrincipal: Principal;
    allocatedBy: Principal;
    quantity: bigint;
}
export interface UserProfile {
    employeeCode: string;
    name: string;
    headQuarter: string;
}
export interface Product {
    id: ProductId;
    code: string;
    name: string;
    createdBy: Principal;
}
export enum DemandOrderStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum LeaveType {
    WithoutPayLeave = "WithoutPayLeave",
    CasualLeave = "CasualLeave",
    EarnedLeave = "EarnedLeave",
    SickLeave = "SickLeave",
    PrivilegeLeave = "PrivilegeLeave"
}
export enum ManagerRole {
    ASM = "ASM",
    RSM = "RSM"
}
export enum OrderStatus {
    pending = "pending",
    fulfilled = "fulfilled"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addArea(name: string, headquarterId: bigint): Promise<AreaId>;
    addChemist(name: string, areaId: AreaId, address: string, contact: string): Promise<ChemistId>;
    addChemistOrder(chemistId: ChemistId, date: string, productId: ProductId, quantity: bigint, scheme: string): Promise<void>;
    addDoctor(name: string, qualification: string, station: string, specialization: string, areaId: AreaId, mobileNumber: [] | [string], dob: [] | [string]): Promise<DoctorId>;
    addExpenseWithGeoTag(date: string, kmTraveled: bigint, daAmount: bigint, notes: string, taAmountOpt: bigint | null, workingArea: string, daType: string, latitude: number | null, longitude: number | null): Promise<void>;
    addGPSTrace(latitude: number, longitude: number, accuracy: number): Promise<void>;
    addGiftArticle(name: string, description: string): Promise<GiftArticleId>;
    addHeadquarter(name: string): Promise<bigint>;
    addProduct(name: string, code: string): Promise<ProductId>;
    addWorkingPlan(input: WorkingPlanInput): Promise<WorkingPlanId>;
    adminAllotSamples(target: Principal, productId: ProductId, quantity: bigint, date: string): Promise<void>;
    adminAssignManagerAreas(target: Principal, areaIds: Array<AreaId>): Promise<void>;
    adminCreateOrUpdateMRProfile(mrPrincipal: Principal, employeeCode: string, headQuarter: string, assignedAreas: Array<AreaId>): Promise<void>;
    adminGetAllWorkingPlans(): Promise<Array<WorkingPlan>>;
    adminGetTADASettings(): Promise<TADASettingsV3>;
    adminResetAllReportData(): Promise<void>;
    adminSaveManagerProfile(target: Principal, name: string, employeeCode: string, headQuarter: string, managerRole: ManagerRole): Promise<void>;
    adminSetTADASettings(settings: TADASettingsV3): Promise<void>;
    applyLeave(leaveType: LeaveType, fromDate: string, toDate: string, days: bigint, reason: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkAddDoctors(doctorsInput: Array<DoctorInput>): Promise<Array<DoctorId>>;
    createOrUpdateMRProfile(employeeCode: string, headQuarter: string, assignedAreas: Array<AreaId>): Promise<void>;
    deleteArea(id: AreaId): Promise<void>;
    deleteDoctor(id: DoctorId): Promise<void>;
    deleteGiftArticle(id: GiftArticleId): Promise<void>;
    deleteHeadquarter(id: bigint): Promise<void>;
    deleteMRProfile(mrPrincipal: Principal): Promise<void>;
    deleteManagerProfile(target: Principal): Promise<void>;
    deleteProduct(id: ProductId): Promise<void>;
    deleteWorkingPlan(planId: WorkingPlanId): Promise<void>;
    emergencyRestoreAdmin(): Promise<void>;
    getActiveUserLocations(): Promise<Array<[Principal, LocationData]>>;
    getActivitySummary(date: string): Promise<ActivitySummary>;
    getAllAreas(): Promise<Array<Area>>;
    getAllCRMDemands(): Promise<Array<CRMDemand>>;
    getAllChemists(): Promise<Array<Chemist>>;
    getAllDoctors(): Promise<Array<Doctor>>;
    getAllGiftArticles(): Promise<Array<GiftArticle>>;
    getAllGiftDemandOrders(): Promise<Array<GiftDemandOrder>>;
    getAllGiftDistributions(): Promise<Array<GiftDistribution>>;
    getAllHeadquarters(): Promise<Array<Headquarter>>;
    getAllLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>>;
    getAllMRProfiles(): Promise<Array<[Principal, MRProfile]>>;
    getAllManagerProfiles(): Promise<Array<[Principal, ManagerProfile]>>;
    getAllPendingUsers(): Promise<Array<Principal>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllSampleAllotments(): Promise<Array<SampleAllotment>>;
    getAllSampleDemandOrders(): Promise<Array<SampleDemandOrder>>;
    getAllUserLatestLocations(): Promise<Array<[Principal, LocationData]>>;
    getAllUserLatestLocationsByRole(): Promise<Array<[Principal, LocationData]>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerRoleInfo(): Promise<{
        managerRole?: string;
        baseRole: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChemistOrders(): Promise<Array<ChemistOrder>>;
    getChemistsByArea(areaId: AreaId): Promise<Array<Chemist>>;
    getDetailingEntries(): Promise<Array<DetailingEntry>>;
    getDoctorsByArea(areaId: AreaId): Promise<Array<Doctor>>;
    getExpenseEntries(): Promise<Array<ExpenseEntry>>;
    getGPSTraces(user: Principal): Promise<Array<GPSTrace>>;
    getLatestLocation(user: Principal): Promise<LocationData | null>;
    getLeaveHistory(): Promise<Array<LeaveEntry>>;
    getMRProfile(): Promise<MRProfile>;
    getManagerAreas(target: Principal): Promise<ManagerAreaAssignment>;
    getManagerProfile(): Promise<ManagerProfile | null>;
    getMyAllotments(): Promise<Array<SampleAllotment>>;
    getMyCRMDemands(): Promise<Array<CRMDemand>>;
    getMyGiftDemandOrders(): Promise<Array<GiftDemandOrder>>;
    getMyGiftDistributions(): Promise<Array<GiftDistribution>>;
    getMySampleBalance(): Promise<Array<SampleBalance>>;
    getMySampleDemandOrders(): Promise<Array<SampleDemandOrder>>;
    getMyWorkingPlans(): Promise<Array<WorkingPlan>>;
    getSampleEntries(): Promise<Array<SampleEntry>>;
    getTeamDetailingEntries(): Promise<Array<[Principal, Array<DetailingEntry>]>>;
    getTeamExpenseEntries(): Promise<Array<[Principal, Array<ExpenseEntry>]>>;
    getTeamLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTraceBetweenTimes(user: Principal, startTime: bigint, endTime: bigint): Promise<Array<GPSTrace>>;
    isAdminInitialized(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    logDetailing(doctorId: DoctorId, date: string, productIds: Array<ProductId>): Promise<void>;
    logGiftDistribution(doctorId: DoctorId, doctorName: string, giftArticleId: GiftArticleId, giftArticleName: string, quantity: bigint, date: string): Promise<void>;
    logSample(doctorId: DoctorId, date: string, productId: ProductId, quantity: bigint): Promise<void>;
    raiseCRMDemand(doctorId: DoctorId, doctorName: string, amount: bigint, notes: string, date: string, raiserName: string): Promise<void>;
    raiseGiftDemandOrder(giftArticleId: GiftArticleId, giftArticleName: string, quantity: bigint, notes: string, date: string): Promise<void>;
    raiseSampleDemandOrder(productId: ProductId, requestedQty: bigint, date: string, notes: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveManagerProfile(name: string, employeeCode: string, headQuarter: string, managerRole: ManagerRole): Promise<void>;
    updateArea(id: AreaId, name: string, headquarterId: bigint): Promise<void>;
    updateCRMDemandStatus(demandId: CRMDemandId, newStatus: CRMDemandStatus, adminRemarks: string): Promise<void>;
    updateDoctor(id: DoctorId, name: string, qualification: string, station: string, specialization: string, areaId: AreaId, mobileNumber: [] | [string], dob: [] | [string]): Promise<void>;
    updateGiftArticle(id: GiftArticleId, name: string, description: string): Promise<void>;
    updateGiftDemandOrderStatus(orderId: GiftDemandOrderId, newStatus: GiftDemandOrderStatus, adminRemarks: string): Promise<void>;
    updateHeadquarter(id: bigint, name: string): Promise<void>;
    updateLatestLocation(location: LocationData): Promise<void>;
    updateLeaveStatus(mrPrincipal: Principal, leaveIndex: bigint, newStatus: LeaveStatus): Promise<void>;
    updateLeaveStatusByManager(mrPrincipal: Principal, leaveIndex: bigint, newStatus: LeaveStatus): Promise<void>;
    updateProduct(id: ProductId, name: string, code: string): Promise<void>;
    updateSampleDemandOrderStatus(orderId: bigint, newStatus: DemandOrderStatus): Promise<void>;
}
import type { ActivitySummary as _ActivitySummary, CRMDemand as _CRMDemand, CRMDemandId as _CRMDemandId, CRMDemandStatus as _CRMDemandStatus, ChemistId as _ChemistId, ChemistOrder as _ChemistOrder, DemandOrderStatus as _DemandOrderStatus, DoctorId as _DoctorId, ExpenseEntry as _ExpenseEntry, GiftArticleId as _GiftArticleId, GiftDemandOrder as _GiftDemandOrder, GiftDemandOrderId as _GiftDemandOrderId, GiftDemandOrderStatus as _GiftDemandOrderStatus, LeaveEntry as _LeaveEntry, LeaveStatus as _LeaveStatus, LeaveType as _LeaveType, LocationData as _LocationData, ManagerProfile as _ManagerProfile, ManagerRole as _ManagerRole, OrderStatus as _OrderStatus, ProductId as _ProductId, SampleDemandOrder as _SampleDemandOrder, UserProfile as _UserProfile, UserRole as _UserRole, WorkingPlan as _WorkingPlan, WorkingPlanId as _WorkingPlanId, WorkingPlanInput as _WorkingPlanInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addArea(arg0: string, arg1: bigint): Promise<AreaId> {
        if (this.processError) {
            try {
                const result = await this.actor.addArea(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArea(arg0, arg1);
            return result;
        }
    }
    async addChemist(arg0: string, arg1: AreaId, arg2: string, arg3: string): Promise<ChemistId> {
        if (this.processError) {
            try {
                const result = await this.actor.addChemist(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChemist(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addChemistOrder(arg0: ChemistId, arg1: string, arg2: ProductId, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChemistOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChemistOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addDoctor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: AreaId, arg5: [] | [string], arg6: [] | [string]): Promise<DoctorId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addExpenseWithGeoTag(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint | null, arg5: string, arg6: string, arg7: number | null, arg8: number | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseWithGeoTag(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseWithGeoTag(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async addGPSTrace(arg0: number, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGPSTrace(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGPSTrace(arg0, arg1, arg2);
            return result;
        }
    }
    async addGiftArticle(arg0: string, arg1: string): Promise<GiftArticleId> {
        if (this.processError) {
            try {
                const result = await this.actor.addGiftArticle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGiftArticle(arg0, arg1);
            return result;
        }
    }
    async addHeadquarter(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeadquarter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeadquarter(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1);
            return result;
        }
    }
    async addWorkingPlan(arg0: WorkingPlanInput): Promise<WorkingPlanId> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkingPlan(to_candid_WorkingPlanInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkingPlan(to_candid_WorkingPlanInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminAllotSamples(arg0: Principal, arg1: ProductId, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAllotSamples(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAllotSamples(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminAssignManagerAreas(arg0: Principal, arg1: Array<AreaId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignManagerAreas(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignManagerAreas(arg0, arg1);
            return result;
        }
    }
    async adminCreateOrUpdateMRProfile(arg0: Principal, arg1: string, arg2: string, arg3: Array<AreaId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateOrUpdateMRProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateOrUpdateMRProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminGetAllWorkingPlans(): Promise<Array<WorkingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllWorkingPlans();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllWorkingPlans();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetTADASettings(): Promise<TADASettingsV3> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetTADASettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetTADASettings();
            return result;
        }
    }
    async adminResetAllReportData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetAllReportData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetAllReportData();
            return result;
        }
    }
    async adminSaveManagerProfile(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: ManagerRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSaveManagerProfile(arg0, arg1, arg2, arg3, to_candid_ManagerRole_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSaveManagerProfile(arg0, arg1, arg2, arg3, to_candid_ManagerRole_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async adminSetTADASettings(arg0: TADASettingsV3): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetTADASettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetTADASettings(arg0);
            return result;
        }
    }
    async applyLeave(arg0: LeaveType, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyLeave(to_candid_LeaveType_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyLeave(to_candid_LeaveType_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAddDoctors(arg0: Array<DoctorInput>): Promise<Array<DoctorId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddDoctors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddDoctors(arg0);
            return result;
        }
    }
    async createOrUpdateMRProfile(arg0: string, arg1: string, arg2: Array<AreaId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateMRProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateMRProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteArea(arg0: AreaId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArea(arg0);
            return result;
        }
    }
    async deleteDoctor(arg0: DoctorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteGiftArticle(arg0: GiftArticleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGiftArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGiftArticle(arg0);
            return result;
        }
    }
    async deleteHeadquarter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHeadquarter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHeadquarter(arg0);
            return result;
        }
    }
    async deleteMRProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMRProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMRProfile(arg0);
            return result;
        }
    }
    async deleteManagerProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManagerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManagerProfile(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteWorkingPlan(arg0: WorkingPlanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkingPlan(arg0);
            return result;
        }
    }
    async emergencyRestoreAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.emergencyRestoreAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emergencyRestoreAdmin();
            return result;
        }
    }
    async getActiveUserLocations(): Promise<Array<[Principal, LocationData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveUserLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveUserLocations();
            return result;
        }
    }
    async getActivitySummary(arg0: string): Promise<ActivitySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitySummary(arg0);
                return from_candid_ActivitySummary_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitySummary(arg0);
            return from_candid_ActivitySummary_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAreas(): Promise<Array<Area>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAreas();
            return result;
        }
    }
    async getAllCRMDemands(): Promise<Array<CRMDemand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCRMDemands();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCRMDemands();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChemists(): Promise<Array<Chemist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChemists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChemists();
            return result;
        }
    }
    async getAllDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return result;
        }
    }
    async getAllGiftArticles(): Promise<Array<GiftArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGiftArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGiftArticles();
            return result;
        }
    }
    async getAllGiftDemandOrders(): Promise<Array<GiftDemandOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGiftDemandOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGiftDemandOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGiftDistributions(): Promise<Array<GiftDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGiftDistributions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGiftDistributions();
            return result;
        }
    }
    async getAllHeadquarters(): Promise<Array<Headquarter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHeadquarters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHeadquarters();
            return result;
        }
    }
    async getAllLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaveApplications();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaveApplications();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMRProfiles(): Promise<Array<[Principal, MRProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMRProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMRProfiles();
            return result;
        }
    }
    async getAllManagerProfiles(): Promise<Array<[Principal, ManagerProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllManagerProfiles();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllManagerProfiles();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingUsers();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllSampleAllotments(): Promise<Array<SampleAllotment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSampleAllotments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSampleAllotments();
            return result;
        }
    }
    async getAllSampleDemandOrders(): Promise<Array<SampleDemandOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSampleDemandOrders();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSampleDemandOrders();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserLatestLocations(): Promise<Array<[Principal, LocationData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserLatestLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserLatestLocations();
            return result;
        }
    }
    async getAllUserLatestLocationsByRole(): Promise<Array<[Principal, LocationData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserLatestLocationsByRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserLatestLocationsByRole();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerRoleInfo(): Promise<{
        managerRole?: string;
        baseRole: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRoleInfo();
                return from_candid_record_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRoleInfo();
            return from_candid_record_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChemistOrders(): Promise<Array<ChemistOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChemistOrders();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChemistOrders();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChemistsByArea(arg0: AreaId): Promise<Array<Chemist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChemistsByArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChemistsByArea(arg0);
            return result;
        }
    }
    async getDetailingEntries(): Promise<Array<DetailingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetailingEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetailingEntries();
            return result;
        }
    }
    async getDoctorsByArea(arg0: AreaId): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorsByArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorsByArea(arg0);
            return result;
        }
    }
    async getExpenseEntries(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseEntries();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseEntries();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGPSTraces(arg0: Principal): Promise<Array<GPSTrace>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGPSTraces(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGPSTraces(arg0);
            return result;
        }
    }
    async getLatestLocation(arg0: Principal): Promise<LocationData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestLocation(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestLocation(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveHistory(): Promise<Array<LeaveEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveHistory();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveHistory();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMRProfile(): Promise<MRProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMRProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMRProfile();
            return result;
        }
    }
    async getManagerAreas(arg0: Principal): Promise<ManagerAreaAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagerAreas(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagerAreas(arg0);
            return result;
        }
    }
    async getManagerProfile(): Promise<ManagerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagerProfile();
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagerProfile();
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAllotments(): Promise<Array<SampleAllotment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAllotments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAllotments();
            return result;
        }
    }
    async getMyCRMDemands(): Promise<Array<CRMDemand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCRMDemands();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCRMDemands();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGiftDemandOrders(): Promise<Array<GiftDemandOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGiftDemandOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGiftDemandOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGiftDistributions(): Promise<Array<GiftDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGiftDistributions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGiftDistributions();
            return result;
        }
    }
    async getMySampleBalance(): Promise<Array<SampleBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySampleBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySampleBalance();
            return result;
        }
    }
    async getMySampleDemandOrders(): Promise<Array<SampleDemandOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySampleDemandOrders();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySampleDemandOrders();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkingPlans(): Promise<Array<WorkingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkingPlans();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkingPlans();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSampleEntries(): Promise<Array<SampleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleEntries();
            return result;
        }
    }
    async getTeamDetailingEntries(): Promise<Array<[Principal, Array<DetailingEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamDetailingEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamDetailingEntries();
            return result;
        }
    }
    async getTeamExpenseEntries(): Promise<Array<[Principal, Array<ExpenseEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamExpenseEntries();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamExpenseEntries();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamLeaveApplications(): Promise<Array<[Principal, Array<LeaveEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamLeaveApplications();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamLeaveApplications();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTraceBetweenTimes(arg0: Principal, arg1: bigint, arg2: bigint): Promise<Array<GPSTrace>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTraceBetweenTimes(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTraceBetweenTimes(arg0, arg1, arg2);
            return result;
        }
    }
    async isAdminInitialized(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminInitialized();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminInitialized();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logDetailing(arg0: DoctorId, arg1: string, arg2: Array<ProductId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDetailing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDetailing(arg0, arg1, arg2);
            return result;
        }
    }
    async logGiftDistribution(arg0: DoctorId, arg1: string, arg2: GiftArticleId, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logGiftDistribution(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logGiftDistribution(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async logSample(arg0: DoctorId, arg1: string, arg2: ProductId, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSample(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSample(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async raiseCRMDemand(arg0: DoctorId, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.raiseCRMDemand(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.raiseCRMDemand(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async raiseGiftDemandOrder(arg0: GiftArticleId, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.raiseGiftDemandOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.raiseGiftDemandOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async raiseSampleDemandOrder(arg0: ProductId, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.raiseSampleDemandOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.raiseSampleDemandOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveManagerProfile(arg0: string, arg1: string, arg2: string, arg3: ManagerRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveManagerProfile(arg0, arg1, arg2, to_candid_ManagerRole_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveManagerProfile(arg0, arg1, arg2, to_candid_ManagerRole_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateArea(arg0: AreaId, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArea(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArea(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCRMDemandStatus(arg0: CRMDemandId, arg1: CRMDemandStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCRMDemandStatus(arg0, to_candid_CRMDemandStatus_n63(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCRMDemandStatus(arg0, to_candid_CRMDemandStatus_n63(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateDoctor(arg0: DoctorId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: AreaId, arg6: [] | [string], arg7: [] | [string]): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateGiftArticle(arg0: GiftArticleId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGiftArticle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGiftArticle(arg0, arg1, arg2);
            return result;
        }
    }
    async updateGiftDemandOrderStatus(arg0: GiftDemandOrderId, arg1: GiftDemandOrderStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGiftDemandOrderStatus(arg0, to_candid_GiftDemandOrderStatus_n65(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGiftDemandOrderStatus(arg0, to_candid_GiftDemandOrderStatus_n65(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateHeadquarter(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeadquarter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeadquarter(arg0, arg1);
            return result;
        }
    }
    async updateLatestLocation(arg0: LocationData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLatestLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLatestLocation(arg0);
            return result;
        }
    }
    async updateLeaveStatus(arg0: Principal, arg1: bigint, arg2: LeaveStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveStatus(arg0, arg1, to_candid_LeaveStatus_n66(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveStatus(arg0, arg1, to_candid_LeaveStatus_n66(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateLeaveStatusByManager(arg0: Principal, arg1: bigint, arg2: LeaveStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveStatusByManager(arg0, arg1, to_candid_LeaveStatus_n66(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveStatusByManager(arg0, arg1, to_candid_LeaveStatus_n66(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSampleDemandOrderStatus(arg0: bigint, arg1: DemandOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleDemandOrderStatus(arg0, to_candid_DemandOrderStatus_n67(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleDemandOrderStatus(arg0, to_candid_DemandOrderStatus_n67(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivitySummary_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivitySummary): ActivitySummary {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CRMDemandStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CRMDemandStatus): CRMDemandStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CRMDemand_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CRMDemand): CRMDemand {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ChemistOrder_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChemistOrder): ChemistOrder {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_DemandOrderStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DemandOrderStatus): DemandOrderStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseEntry_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseEntry): ExpenseEntry {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_GiftDemandOrderStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftDemandOrderStatus): GiftDemandOrderStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_GiftDemandOrder_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftDemandOrder): GiftDemandOrder {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveEntry_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveEntry): LeaveEntry {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveType): LeaveType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerProfile): ManagerProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerRole): ManagerRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_SampleDemandOrder_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleDemandOrder): SampleDemandOrder {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_WorkingPlan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkingPlan): WorkingPlan {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocationData]): LocationData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ManagerProfile]): ManagerProfile | null {
    return value.length === 0 ? null : from_candid_ManagerProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leaveBalance: Array<[_LeaveType, bigint]>;
    samplesGiven: bigint;
    dailyExpense: bigint;
    doctorsVisited: bigint;
    chemistOrders: bigint;
}): {
    leaveBalance: Array<[LeaveType, bigint]>;
    samplesGiven: bigint;
    dailyExpense: bigint;
    doctorsVisited: bigint;
    chemistOrders: bigint;
} {
    return {
        leaveBalance: from_candid_vec_n17(_uploadFile, _downloadFile, value.leaveBalance),
        samplesGiven: value.samplesGiven,
        dailyExpense: value.dailyExpense,
        doctorsVisited: value.doctorsVisited,
        chemistOrders: value.chemistOrders
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CRMDemandId;
    status: _CRMDemandStatus;
    doctorId: _DoctorId;
    date: string;
    notes: string;
    raisedBy: Principal;
    doctorName: string;
    amount: bigint;
    raiserName: string;
    adminRemarks: string;
}): {
    id: CRMDemandId;
    status: CRMDemandStatus;
    doctorId: DoctorId;
    date: string;
    notes: string;
    raisedBy: Principal;
    doctorName: string;
    amount: bigint;
    raiserName: string;
    adminRemarks: string;
} {
    return {
        id: value.id,
        status: from_candid_CRMDemandStatus_n24(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        date: value.date,
        notes: value.notes,
        raisedBy: value.raisedBy,
        doctorName: value.doctorName,
        amount: value.amount,
        raiserName: value.raiserName,
        adminRemarks: value.adminRemarks
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GiftDemandOrderId;
    status: _GiftDemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    giftArticleName: string;
    notes: string;
    giftArticleId: _GiftArticleId;
    quantity: bigint;
    adminRemarks: string;
}): {
    id: GiftDemandOrderId;
    status: GiftDemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    giftArticleName: string;
    notes: string;
    giftArticleId: GiftArticleId;
    quantity: bigint;
    adminRemarks: string;
} {
    return {
        id: value.id,
        status: from_candid_GiftDemandOrderStatus_n29(_uploadFile, _downloadFile, value.status),
        mrPrincipal: value.mrPrincipal,
        date: value.date,
        giftArticleName: value.giftArticleName,
        notes: value.notes,
        giftArticleId: value.giftArticleId,
        quantity: value.quantity,
        adminRemarks: value.adminRemarks
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeaveStatus;
    days: bigint;
    toDate: string;
    fromDate: string;
    leaveType: _LeaveType;
    reason: string;
}): {
    status: LeaveStatus;
    days: bigint;
    toDate: string;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
} {
    return {
        status: from_candid_LeaveStatus_n35(_uploadFile, _downloadFile, value.status),
        days: value.days,
        toDate: value.toDate,
        fromDate: value.fromDate,
        leaveType: from_candid_LeaveType_n19(_uploadFile, _downloadFile, value.leaveType),
        reason: value.reason
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    managerRole: _ManagerRole;
    employeeCode: string;
    name: string;
    headQuarter: string;
}): {
    managerRole: ManagerRole;
    employeeCode: string;
    name: string;
    headQuarter: string;
} {
    return {
        managerRole: from_candid_ManagerRole_n40(_uploadFile, _downloadFile, value.managerRole),
        employeeCode: value.employeeCode,
        name: value.name,
        headQuarter: value.headQuarter
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    productId: _ProductId;
    requestedQty: bigint;
    notes: string;
}): {
    id: bigint;
    status: DemandOrderStatus;
    mrPrincipal: Principal;
    date: string;
    productId: ProductId;
    requestedQty: bigint;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_DemandOrderStatus_n45(_uploadFile, _downloadFile, value.status),
        mrPrincipal: value.mrPrincipal,
        date: value.date,
        productId: value.productId,
        requestedQty: value.requestedQty,
        notes: value.notes
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    managerRole: [] | [string];
    baseRole: string;
}): {
    managerRole?: string;
    baseRole: string;
} {
    return {
        managerRole: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.managerRole)),
        baseRole: value.baseRole
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    scheme: string;
    date: string;
    productId: _ProductId;
    chemistId: _ChemistId;
    quantity: bigint;
}): {
    status: OrderStatus;
    scheme: string;
    date: string;
    productId: ProductId;
    chemistId: ChemistId;
    quantity: bigint;
} {
    return {
        status: from_candid_OrderStatus_n53(_uploadFile, _downloadFile, value.status),
        scheme: value.scheme,
        date: value.date,
        productId: value.productId,
        chemistId: value.chemistId,
        quantity: value.quantity
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: [] | [number];
    daType: string;
    daAmount: bigint;
    date: string;
    kmTraveled: bigint;
    longitude: [] | [number];
    notes: string;
    workingArea: string;
    taAmount: bigint;
}): {
    latitude?: number;
    daType: string;
    daAmount: bigint;
    date: string;
    kmTraveled: bigint;
    longitude?: number;
    notes: string;
    workingArea: string;
    taAmount: bigint;
} {
    return {
        latitude: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.latitude)),
        daType: value.daType,
        daAmount: value.daAmount,
        date: value.date,
        kmTraveled: value.kmTraveled,
        longitude: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.longitude)),
        notes: value.notes,
        workingArea: value.workingArea,
        taAmount: value.taAmount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkingPlanId;
    content: string;
    date: string;
    createdAt: bigint;
    workingMode: string;
    workingWith: [] | [string];
    stationType: string;
    principalId: Principal;
}): {
    id: WorkingPlanId;
    content: string;
    date: string;
    createdAt: bigint;
    workingMode: string;
    workingWith?: string;
    stationType: string;
    principalId: Principal;
} {
    return {
        id: value.id,
        content: value.content,
        date: value.date,
        createdAt: value.createdAt,
        workingMode: value.workingMode,
        workingWith: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.workingWith)),
        stationType: value.stationType,
        principalId: value.principalId
    };
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_LeaveType, bigint]): [LeaveType, bigint] {
    return [
        from_candid_LeaveType_n19(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_LeaveEntry>]): [Principal, Array<LeaveEntry>] {
    return [
        value[0],
        from_candid_vec_n32(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _ManagerProfile]): [Principal, ManagerProfile] {
    return [
        value[0],
        from_candid_ManagerProfile_n38(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_ExpenseEntry>]): [Principal, Array<ExpenseEntry>] {
    return [
        value[0],
        from_candid_vec_n55(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    WithoutPayLeave: null;
} | {
    CasualLeave: null;
} | {
    EarnedLeave: null;
} | {
    SickLeave: null;
} | {
    PrivilegeLeave: null;
}): LeaveType {
    return "WithoutPayLeave" in value ? LeaveType.WithoutPayLeave : "CasualLeave" in value ? LeaveType.CasualLeave : "EarnedLeave" in value ? LeaveType.EarnedLeave : "SickLeave" in value ? LeaveType.SickLeave : "PrivilegeLeave" in value ? LeaveType.PrivilegeLeave : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): DemandOrderStatus {
    return "Approved" in value ? DemandOrderStatus.Approved : "Rejected" in value ? DemandOrderStatus.Rejected : "Pending" in value ? DemandOrderStatus.Pending : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ASM: null;
} | {
    RSM: null;
}): ManagerRole {
    return "ASM" in value ? ManagerRole.ASM : "RSM" in value ? ManagerRole.RSM : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    fulfilled: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "fulfilled" in value ? OrderStatus.fulfilled : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_LeaveType, bigint]>): Array<[LeaveType, bigint]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CRMDemand>): Array<CRMDemand> {
    return value.map((x)=>from_candid_CRMDemand_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GiftDemandOrder>): Array<GiftDemandOrder> {
    return value.map((x)=>from_candid_GiftDemandOrder_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_LeaveEntry>]>): Array<[Principal, Array<LeaveEntry>]> {
    return value.map((x)=>from_candid_tuple_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveEntry>): Array<LeaveEntry> {
    return value.map((x)=>from_candid_LeaveEntry_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _ManagerProfile]>): Array<[Principal, ManagerProfile]> {
    return value.map((x)=>from_candid_tuple_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SampleDemandOrder>): Array<SampleDemandOrder> {
    return value.map((x)=>from_candid_SampleDemandOrder_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkingPlan>): Array<WorkingPlan> {
    return value.map((x)=>from_candid_WorkingPlan_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChemistOrder>): Array<ChemistOrder> {
    return value.map((x)=>from_candid_ChemistOrder_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseEntry>): Array<ExpenseEntry> {
    return value.map((x)=>from_candid_ExpenseEntry_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_ExpenseEntry>]>): Array<[Principal, Array<ExpenseEntry>]> {
    return value.map((x)=>from_candid_tuple_n62(_uploadFile, _downloadFile, x));
}
function to_candid_CRMDemandStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CRMDemandStatus): _CRMDemandStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_DemandOrderStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DemandOrderStatus): _DemandOrderStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_GiftDemandOrderStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftDemandOrderStatus): _GiftDemandOrderStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): _LeaveType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ManagerRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerRole): _ManagerRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_WorkingPlanInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkingPlanInput): _WorkingPlanInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    date: string;
    workingMode: string;
    workingWith?: string;
    stationType: string;
}): {
    content: string;
    date: string;
    workingMode: string;
    workingWith: [] | [string];
    stationType: string;
} {
    return {
        content: value.content,
        date: value.date,
        workingMode: value.workingMode,
        workingWith: value.workingWith ? candid_some(value.workingWith) : candid_none(),
        stationType: value.stationType
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerRole): {
    ASM: null;
} | {
    RSM: null;
} {
    return value == ManagerRole.ASM ? {
        ASM: null
    } : value == ManagerRole.RSM ? {
        RSM: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): {
    WithoutPayLeave: null;
} | {
    CasualLeave: null;
} | {
    EarnedLeave: null;
} | {
    SickLeave: null;
} | {
    PrivilegeLeave: null;
} {
    return value == LeaveType.WithoutPayLeave ? {
        WithoutPayLeave: null
    } : value == LeaveType.CasualLeave ? {
        CasualLeave: null
    } : value == LeaveType.EarnedLeave ? {
        EarnedLeave: null
    } : value == LeaveType.SickLeave ? {
        SickLeave: null
    } : value == LeaveType.PrivilegeLeave ? {
        PrivilegeLeave: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DemandOrderStatus): {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == DemandOrderStatus.Approved ? {
        Approved: null
    } : value == DemandOrderStatus.Rejected ? {
        Rejected: null
    } : value == DemandOrderStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
